package com.zhiye.common.bean;

import java.io.Serializable;
import java.util.Date;

public class ZyArticle implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.articleId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Long articleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.title
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.come_from
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String comeFrom;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.status
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer typeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.user_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer partmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.img_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String imgFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Date updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.keywords
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String keywords;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.img_url
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String imgUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.article_type
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String articleType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.inner_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String innerFlag;

    private int click;
    public int getClick() {
		return click;
	}

	public void setClick(int click) {
		this.click = click;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.articleId
     *
     * @return the value of zy_article.articleId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.articleId
     *
     * @param articleId the value for zy_article.articleId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.title
     *
     * @return the value of zy_article.title
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.title
     *
     * @param title the value for zy_article.title
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.come_from
     *
     * @return the value of zy_article.come_from
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getComeFrom() {
        return comeFrom;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.come_from
     *
     * @param comeFrom the value for zy_article.come_from
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setComeFrom(String comeFrom) {
        this.comeFrom = comeFrom;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.status
     *
     * @return the value of zy_article.status
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.status
     *
     * @param status the value for zy_article.status
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.typeId
     *
     * @return the value of zy_article.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.typeId
     *
     * @param typeId the value for zy_article.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.user_id
     *
     * @return the value of zy_article.user_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.user_id
     *
     * @param userId the value for zy_article.user_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.partment_id
     *
     * @return the value of zy_article.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getPartmentId() {
        return partmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.partment_id
     *
     * @param partmentId the value for zy_article.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setPartmentId(Integer partmentId) {
        this.partmentId = partmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.img_flag
     *
     * @return the value of zy_article.img_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getImgFlag() {
        return imgFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.img_flag
     *
     * @param imgFlag the value for zy_article.img_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setImgFlag(String imgFlag) {
        this.imgFlag = imgFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.create_time
     *
     * @return the value of zy_article.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.create_time
     *
     * @param createTime the value for zy_article.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.update_time
     *
     * @return the value of zy_article.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.update_time
     *
     * @param updateTime the value for zy_article.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.keywords
     *
     * @return the value of zy_article.keywords
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.keywords
     *
     * @param keywords the value for zy_article.keywords
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.img_url
     *
     * @return the value of zy_article.img_url
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.img_url
     *
     * @param imgUrl the value for zy_article.img_url
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.article_type
     *
     * @return the value of zy_article.article_type
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.article_type
     *
     * @param articleType the value for zy_article.article_type
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setArticleType(String articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.inner_flag
     *
     * @return the value of zy_article.inner_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getInnerFlag() {
        return innerFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.inner_flag
     *
     * @param innerFlag the value for zy_article.inner_flag
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setInnerFlag(String innerFlag) {
        this.innerFlag = innerFlag;
    }
    
}