package com.zhiye.common.bean;

import java.io.Serializable;
import java.util.Date;

public class ZyArticleType implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article_type.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer typeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article_type.parent_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer parentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article_type.type_name
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String typeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article_type.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Date createTime;

    private String link;
    
    private String visiable;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article_type.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Date updateTime;

    private String type;
    public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article_type.typeId
     *
     * @return the value of zy_article_type.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article_type.typeId
     *
     * @param typeId the value for zy_article_type.typeId
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article_type.parent_id
     *
     * @return the value of zy_article_type.parent_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article_type.parent_id
     *
     * @param parentId the value for zy_article_type.parent_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article_type.type_name
     *
     * @return the value of zy_article_type.type_name
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article_type.type_name
     *
     * @param typeName the value for zy_article_type.type_name
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article_type.create_time
     *
     * @return the value of zy_article_type.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article_type.create_time
     *
     * @param createTime the value for zy_article_type.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article_type.update_time
     *
     * @return the value of zy_article_type.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article_type.update_time
     *
     * @param updateTime the value for zy_article_type.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getVisiable() {
		return visiable;
	}

	public void setVisiable(String visiable) {
		this.visiable = visiable;
	}
}