package com.zhiye.common.bean;

public class ZyArticleWithBLOBs extends ZyArticle {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.content
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String content;
    private String typeName;
    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String remarks;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_article.description
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.content
     *
     * @return the value of zy_article.content
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.content
     *
     * @param content the value for zy_article.content
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.remarks
     *
     * @return the value of zy_article.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.remarks
     *
     * @param remarks the value for zy_article.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_article.description
     *
     * @return the value of zy_article.description
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_article.description
     *
     * @param description the value for zy_article.description
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }
}