package com.zhiye.common.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZyArticleParams implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public ZyArticleParams() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    protected ZyArticleParams(ZyArticleParams example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_article
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("articleId is null");
            return this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("articleId is not null");
            return this;
        }

        public Criteria andArticleIdEqualTo(Long value) {
            addCriterion("articleId =", value, "articleId");
            return this;
        }

        public Criteria andArticleIdNotEqualTo(Long value) {
            addCriterion("articleId <>", value, "articleId");
            return this;
        }

        public Criteria andArticleIdGreaterThan(Long value) {
            addCriterion("articleId >", value, "articleId");
            return this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("articleId >=", value, "articleId");
            return this;
        }

        public Criteria andArticleIdLessThan(Long value) {
            addCriterion("articleId <", value, "articleId");
            return this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(Long value) {
            addCriterion("articleId <=", value, "articleId");
            return this;
        }

        public Criteria andArticleIdIn(List values) {
            addCriterion("articleId in", values, "articleId");
            return this;
        }

        public Criteria andArticleIdNotIn(List values) {
            addCriterion("articleId not in", values, "articleId");
            return this;
        }

        public Criteria andArticleIdBetween(Long value1, Long value2) {
            addCriterion("articleId between", value1, value2, "articleId");
            return this;
        }

        public Criteria andArticleIdNotBetween(Long value1, Long value2) {
            addCriterion("articleId not between", value1, value2, "articleId");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }

        public Criteria andComeFromIsNull() {
            addCriterion("come_from is null");
            return this;
        }

        public Criteria andComeFromIsNotNull() {
            addCriterion("come_from is not null");
            return this;
        }

        public Criteria andComeFromEqualTo(String value) {
            addCriterion("come_from =", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromNotEqualTo(String value) {
            addCriterion("come_from <>", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromGreaterThan(String value) {
            addCriterion("come_from >", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromGreaterThanOrEqualTo(String value) {
            addCriterion("come_from >=", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromLessThan(String value) {
            addCriterion("come_from <", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromLessThanOrEqualTo(String value) {
            addCriterion("come_from <=", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromLike(String value) {
            addCriterion("come_from like", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromNotLike(String value) {
            addCriterion("come_from not like", value, "comeFrom");
            return this;
        }

        public Criteria andComeFromIn(List values) {
            addCriterion("come_from in", values, "comeFrom");
            return this;
        }

        public Criteria andComeFromNotIn(List values) {
            addCriterion("come_from not in", values, "comeFrom");
            return this;
        }

        public Criteria andComeFromBetween(String value1, String value2) {
            addCriterion("come_from between", value1, value2, "comeFrom");
            return this;
        }

        public Criteria andComeFromNotBetween(String value1, String value2) {
            addCriterion("come_from not between", value1, value2, "comeFrom");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("typeId is null");
            return this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("typeId is not null");
            return this;
        }

        public Criteria andTypeIdEqualTo(Integer value) {
            addCriterion("typeId =", value, "typeId");
            return this;
        }

        public Criteria andTypeIdNotEqualTo(Integer value) {
            addCriterion("typeId <>", value, "typeId");
            return this;
        }

        public Criteria andTypeIdGreaterThan(Integer value) {
            addCriterion("typeId >", value, "typeId");
            return this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("typeId >=", value, "typeId");
            return this;
        }

        public Criteria andTypeIdLessThan(Integer value) {
            addCriterion("typeId <", value, "typeId");
            return this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("typeId <=", value, "typeId");
            return this;
        }

        public Criteria andTypeIdIn(List values) {
            addCriterion("typeId in", values, "typeId");
            return this;
        }

        public Criteria andTypeIdNotIn(List values) {
            addCriterion("typeId not in", values, "typeId");
            return this;
        }

        public Criteria andTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("typeId between", value1, value2, "typeId");
            return this;
        }

        public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("typeId not between", value1, value2, "typeId");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andPartmentIdIsNull() {
            addCriterion("partment_id is null");
            return this;
        }

        public Criteria andPartmentIdIsNotNull() {
            addCriterion("partment_id is not null");
            return this;
        }

        public Criteria andPartmentIdEqualTo(Integer value) {
            addCriterion("partment_id =", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdNotEqualTo(Integer value) {
            addCriterion("partment_id <>", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdGreaterThan(Integer value) {
            addCriterion("partment_id >", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("partment_id >=", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdLessThan(Integer value) {
            addCriterion("partment_id <", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("partment_id <=", value, "partmentId");
            return this;
        }

        public Criteria andPartmentIdIn(List values) {
            addCriterion("partment_id in", values, "partmentId");
            return this;
        }

        public Criteria andPartmentIdNotIn(List values) {
            addCriterion("partment_id not in", values, "partmentId");
            return this;
        }

        public Criteria andPartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("partment_id between", value1, value2, "partmentId");
            return this;
        }

        public Criteria andPartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("partment_id not between", value1, value2, "partmentId");
            return this;
        }

        public Criteria andImgFlagIsNull() {
            addCriterion("img_flag is null");
            return this;
        }

        public Criteria andImgFlagIsNotNull() {
            addCriterion("img_flag is not null");
            return this;
        }

        public Criteria andImgFlagEqualTo(String value) {
            addCriterion("img_flag =", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagNotEqualTo(String value) {
            addCriterion("img_flag <>", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagGreaterThan(String value) {
            addCriterion("img_flag >", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagGreaterThanOrEqualTo(String value) {
            addCriterion("img_flag >=", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagLessThan(String value) {
            addCriterion("img_flag <", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagLessThanOrEqualTo(String value) {
            addCriterion("img_flag <=", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagLike(String value) {
            addCriterion("img_flag like", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagNotLike(String value) {
            addCriterion("img_flag not like", value, "imgFlag");
            return this;
        }

        public Criteria andImgFlagIn(List values) {
            addCriterion("img_flag in", values, "imgFlag");
            return this;
        }

        public Criteria andImgFlagNotIn(List values) {
            addCriterion("img_flag not in", values, "imgFlag");
            return this;
        }

        public Criteria andImgFlagBetween(String value1, String value2) {
            addCriterion("img_flag between", value1, value2, "imgFlag");
            return this;
        }

        public Criteria andImgFlagNotBetween(String value1, String value2) {
            addCriterion("img_flag not between", value1, value2, "imgFlag");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return this;
        }

        public Criteria andKeywordsIn(List values) {
            addCriterion("keywords in", values, "keywords");
            return this;
        }

        public Criteria andKeywordsNotIn(List values) {
            addCriterion("keywords not in", values, "keywords");
            return this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return this;
        }

        public Criteria andImgUrlIn(List values) {
            addCriterion("img_url in", values, "imgUrl");
            return this;
        }

        public Criteria andImgUrlNotIn(List values) {
            addCriterion("img_url not in", values, "imgUrl");
            return this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return this;
        }

        public Criteria andArticleTypeIsNull() {
            addCriterion("article_type is null");
            return this;
        }

        public Criteria andArticleTypeIsNotNull() {
            addCriterion("article_type is not null");
            return this;
        }

        public Criteria andArticleTypeEqualTo(String value) {
            addCriterion("article_type =", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeNotEqualTo(String value) {
            addCriterion("article_type <>", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeGreaterThan(String value) {
            addCriterion("article_type >", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("article_type >=", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeLessThan(String value) {
            addCriterion("article_type <", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeLessThanOrEqualTo(String value) {
            addCriterion("article_type <=", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeLike(String value) {
            addCriterion("article_type like", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeNotLike(String value) {
            addCriterion("article_type not like", value, "articleType");
            return this;
        }

        public Criteria andArticleTypeIn(List values) {
            addCriterion("article_type in", values, "articleType");
            return this;
        }

        public Criteria andArticleTypeNotIn(List values) {
            addCriterion("article_type not in", values, "articleType");
            return this;
        }

        public Criteria andArticleTypeBetween(String value1, String value2) {
            addCriterion("article_type between", value1, value2, "articleType");
            return this;
        }

        public Criteria andArticleTypeNotBetween(String value1, String value2) {
            addCriterion("article_type not between", value1, value2, "articleType");
            return this;
        }

        public Criteria andInnerFlagIsNull() {
            addCriterion("inner_flag is null");
            return this;
        }

        public Criteria andInnerFlagIsNotNull() {
            addCriterion("inner_flag is not null");
            return this;
        }

        public Criteria andInnerFlagEqualTo(String value) {
            addCriterion("inner_flag =", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagNotEqualTo(String value) {
            addCriterion("inner_flag <>", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagGreaterThan(String value) {
            addCriterion("inner_flag >", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagGreaterThanOrEqualTo(String value) {
            addCriterion("inner_flag >=", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagLessThan(String value) {
            addCriterion("inner_flag <", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagLessThanOrEqualTo(String value) {
            addCriterion("inner_flag <=", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagLike(String value) {
            addCriterion("inner_flag like", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagNotLike(String value) {
            addCriterion("inner_flag not like", value, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagIn(List values) {
            addCriterion("inner_flag in", values, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagNotIn(List values) {
            addCriterion("inner_flag not in", values, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagBetween(String value1, String value2) {
            addCriterion("inner_flag between", value1, value2, "innerFlag");
            return this;
        }

        public Criteria andInnerFlagNotBetween(String value1, String value2) {
            addCriterion("inner_flag not between", value1, value2, "innerFlag");
            return this;
        }
        public Criteria andClickIsNull() {
            addCriterion("click is null");
            return this;
        }

        public Criteria andClickIsNotNull() {
            addCriterion("click is not null");
            return this;
        }

        public Criteria andClickEqualTo(Long value) {
            addCriterion("click =", value, "click");
            return this;
        }

        public Criteria andClickNotEqualTo(Long value) {
            addCriterion("click <>", value, "click");
            return this;
        }

        public Criteria andClickGreaterThan(Long value) {
            addCriterion("click >", value, "click");
            return this;
        }

        public Criteria andClickGreaterThanOrEqualTo(Long value) {
            addCriterion("click >=", value, "click");
            return this;
        }

        public Criteria andClickLessThan(Long value) {
            addCriterion("click <", value, "click");
            return this;
        }

        public Criteria andClickLessThanOrEqualTo(Long value) {
            addCriterion("click <=", value, "click");
            return this;
        }

        public Criteria andClickIn(List values) {
            addCriterion("click in", values, "click");
            return this;
        }

        public Criteria andClickNotIn(List values) {
            addCriterion("click not in", values, "click");
            return this;
        }

        public Criteria andClickBetween(Long value1, Long value2) {
            addCriterion("click between", value1, value2, "click");
            return this;
        }

        public Criteria andClickNotBetween(Long value1, Long value2) {
            addCriterion("click not between", value1, value2, "click");
            return this;
        }
    }
}