package com.zhiye.common.bean;

public class ZyContactAndType {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_contact_and_type.type_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	private Integer typeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_contact_and_type.contact_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	private Integer contactId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_contact_and_type.type_id
	 * @return  the value of zy_contact_and_type.type_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_contact_and_type.type_id
	 * @param typeId  the value for zy_contact_and_type.type_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_contact_and_type.contact_id
	 * @return  the value of zy_contact_and_type.contact_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public Integer getContactId() {
		return contactId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_contact_and_type.contact_id
	 * @param contactId  the value for zy_contact_and_type.contact_id
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}
}