package com.zhiye.common.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZyCorporationProductParams {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public ZyCorporationProductParams() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	protected ZyCorporationProductParams(ZyCorporationProductParams example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andRowidIsNull() {
			addCriterion("RowID is null");
			return this;
		}

		public Criteria andRowidIsNotNull() {
			addCriterion("RowID is not null");
			return this;
		}

		public Criteria andRowidEqualTo(Integer value) {
			addCriterion("RowID =", value, "rowid");
			return this;
		}

		public Criteria andRowidNotEqualTo(Integer value) {
			addCriterion("RowID <>", value, "rowid");
			return this;
		}

		public Criteria andRowidGreaterThan(Integer value) {
			addCriterion("RowID >", value, "rowid");
			return this;
		}

		public Criteria andRowidGreaterThanOrEqualTo(Integer value) {
			addCriterion("RowID >=", value, "rowid");
			return this;
		}

		public Criteria andRowidLessThan(Integer value) {
			addCriterion("RowID <", value, "rowid");
			return this;
		}

		public Criteria andRowidLessThanOrEqualTo(Integer value) {
			addCriterion("RowID <=", value, "rowid");
			return this;
		}

		public Criteria andRowidIn(List values) {
			addCriterion("RowID in", values, "rowid");
			return this;
		}

		public Criteria andRowidNotIn(List values) {
			addCriterion("RowID not in", values, "rowid");
			return this;
		}

		public Criteria andRowidBetween(Integer value1, Integer value2) {
			addCriterion("RowID between", value1, value2, "rowid");
			return this;
		}

		public Criteria andRowidNotBetween(Integer value1, Integer value2) {
			addCriterion("RowID not between", value1, value2, "rowid");
			return this;
		}

		public Criteria andCorportationidIsNull() {
			addCriterion("corportationID is null");
			return this;
		}

		public Criteria andCorportationidIsNotNull() {
			addCriterion("corportationID is not null");
			return this;
		}

		public Criteria andCorportationidEqualTo(String value) {
			addCriterion("corportationID =", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidNotEqualTo(String value) {
			addCriterion("corportationID <>", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidGreaterThan(String value) {
			addCriterion("corportationID >", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidGreaterThanOrEqualTo(String value) {
			addCriterion("corportationID >=", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidLessThan(String value) {
			addCriterion("corportationID <", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidLessThanOrEqualTo(String value) {
			addCriterion("corportationID <=", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidLike(String value) {
			addCriterion("corportationID like", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidNotLike(String value) {
			addCriterion("corportationID not like", value, "corportationid");
			return this;
		}

		public Criteria andCorportationidIn(List values) {
			addCriterion("corportationID in", values, "corportationid");
			return this;
		}

		public Criteria andCorportationidNotIn(List values) {
			addCriterion("corportationID not in", values, "corportationid");
			return this;
		}

		public Criteria andCorportationidBetween(String value1, String value2) {
			addCriterion("corportationID between", value1, value2,
					"corportationid");
			return this;
		}

		public Criteria andCorportationidNotBetween(String value1, String value2) {
			addCriterion("corportationID not between", value1, value2,
					"corportationid");
			return this;
		}

		public Criteria andProductidIsNull() {
			addCriterion("productID is null");
			return this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("productID is not null");
			return this;
		}

		public Criteria andProductidEqualTo(String value) {
			addCriterion("productID =", value, "productid");
			return this;
		}

		public Criteria andProductidNotEqualTo(String value) {
			addCriterion("productID <>", value, "productid");
			return this;
		}

		public Criteria andProductidGreaterThan(String value) {
			addCriterion("productID >", value, "productid");
			return this;
		}

		public Criteria andProductidGreaterThanOrEqualTo(String value) {
			addCriterion("productID >=", value, "productid");
			return this;
		}

		public Criteria andProductidLessThan(String value) {
			addCriterion("productID <", value, "productid");
			return this;
		}

		public Criteria andProductidLessThanOrEqualTo(String value) {
			addCriterion("productID <=", value, "productid");
			return this;
		}

		public Criteria andProductidLike(String value) {
			addCriterion("productID like", value, "productid");
			return this;
		}

		public Criteria andProductidNotLike(String value) {
			addCriterion("productID not like", value, "productid");
			return this;
		}

		public Criteria andProductidIn(List values) {
			addCriterion("productID in", values, "productid");
			return this;
		}

		public Criteria andProductidNotIn(List values) {
			addCriterion("productID not in", values, "productid");
			return this;
		}

		public Criteria andProductidBetween(String value1, String value2) {
			addCriterion("productID between", value1, value2, "productid");
			return this;
		}

		public Criteria andProductidNotBetween(String value1, String value2) {
			addCriterion("productID not between", value1, value2, "productid");
			return this;
		}

		public Criteria andS01IsNull() {
			addCriterion("S01 is null");
			return this;
		}

		public Criteria andS01IsNotNull() {
			addCriterion("S01 is not null");
			return this;
		}

		public Criteria andS01EqualTo(String value) {
			addCriterion("S01 =", value, "s01");
			return this;
		}

		public Criteria andS01NotEqualTo(String value) {
			addCriterion("S01 <>", value, "s01");
			return this;
		}

		public Criteria andS01GreaterThan(String value) {
			addCriterion("S01 >", value, "s01");
			return this;
		}

		public Criteria andS01GreaterThanOrEqualTo(String value) {
			addCriterion("S01 >=", value, "s01");
			return this;
		}

		public Criteria andS01LessThan(String value) {
			addCriterion("S01 <", value, "s01");
			return this;
		}

		public Criteria andS01LessThanOrEqualTo(String value) {
			addCriterion("S01 <=", value, "s01");
			return this;
		}

		public Criteria andS01In(List values) {
			addCriterion("S01 in", values, "s01");
			return this;
		}

		public Criteria andS01NotIn(List values) {
			addCriterion("S01 not in", values, "s01");
			return this;
		}

		public Criteria andS01Between(String value1, String value2) {
			addCriterion("S01 between", value1, value2, "s01");
			return this;
		}

		public Criteria andS01NotBetween(String value1, String value2) {
			addCriterion("S01 not between", value1, value2, "s01");
			return this;
		}

		public Criteria andV01IsNull() {
			addCriterion("V01 is null");
			return this;
		}

		public Criteria andV01IsNotNull() {
			addCriterion("V01 is not null");
			return this;
		}

		public Criteria andV01EqualTo(String value) {
			addCriterion("V01 =", value, "v01");
			return this;
		}

		public Criteria andV01NotEqualTo(String value) {
			addCriterion("V01 <>", value, "v01");
			return this;
		}

		public Criteria andV01GreaterThan(String value) {
			addCriterion("V01 >", value, "v01");
			return this;
		}

		public Criteria andV01GreaterThanOrEqualTo(String value) {
			addCriterion("V01 >=", value, "v01");
			return this;
		}

		public Criteria andV01LessThan(String value) {
			addCriterion("V01 <", value, "v01");
			return this;
		}

		public Criteria andV01LessThanOrEqualTo(String value) {
			addCriterion("V01 <=", value, "v01");
			return this;
		}

		public Criteria andV01In(List values) {
			addCriterion("V01 in", values, "v01");
			return this;
		}

		public Criteria andV01NotIn(List values) {
			addCriterion("V01 not in", values, "v01");
			return this;
		}

		public Criteria andV01Between(String value1, String value2) {
			addCriterion("V01 between", value1, value2, "v01");
			return this;
		}

		public Criteria andV01NotBetween(String value1, String value2) {
			addCriterion("V01 not between", value1, value2, "v01");
			return this;
		}

		public Criteria andActivationIsNull() {
			addCriterion("activation is null");
			return this;
		}

		public Criteria andActivationIsNotNull() {
			addCriterion("activation is not null");
			return this;
		}

		public Criteria andActivationEqualTo(String value) {
			addCriterion("activation =", value, "activation");
			return this;
		}

		public Criteria andActivationNotEqualTo(String value) {
			addCriterion("activation <>", value, "activation");
			return this;
		}

		public Criteria andActivationGreaterThan(String value) {
			addCriterion("activation >", value, "activation");
			return this;
		}

		public Criteria andActivationGreaterThanOrEqualTo(String value) {
			addCriterion("activation >=", value, "activation");
			return this;
		}

		public Criteria andActivationLessThan(String value) {
			addCriterion("activation <", value, "activation");
			return this;
		}

		public Criteria andActivationLessThanOrEqualTo(String value) {
			addCriterion("activation <=", value, "activation");
			return this;
		}

		public Criteria andActivationLike(String value) {
			addCriterion("activation like", value, "activation");
			return this;
		}

		public Criteria andActivationNotLike(String value) {
			addCriterion("activation not like", value, "activation");
			return this;
		}

		public Criteria andActivationIn(List values) {
			addCriterion("activation in", values, "activation");
			return this;
		}

		public Criteria andActivationNotIn(List values) {
			addCriterion("activation not in", values, "activation");
			return this;
		}

		public Criteria andActivationBetween(String value1, String value2) {
			addCriterion("activation between", value1, value2, "activation");
			return this;
		}

		public Criteria andActivationNotBetween(String value1, String value2) {
			addCriterion("activation not between", value1, value2, "activation");
			return this;
		}
	}
}