package com.zhiye.common.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZyCorporationParams {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public ZyCorporationParams() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    protected ZyCorporationParams(ZyCorporationParams example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRowidIsNull() {
            addCriterion("RowID is null");
            return this;
        }

        public Criteria andRowidIsNotNull() {
            addCriterion("RowID is not null");
            return this;
        }

        public Criteria andRowidEqualTo(Integer value) {
            addCriterion("RowID =", value, "rowid");
            return this;
        }

        public Criteria andRowidNotEqualTo(Integer value) {
            addCriterion("RowID <>", value, "rowid");
            return this;
        }

        public Criteria andRowidGreaterThan(Integer value) {
            addCriterion("RowID >", value, "rowid");
            return this;
        }

        public Criteria andRowidGreaterThanOrEqualTo(Integer value) {
            addCriterion("RowID >=", value, "rowid");
            return this;
        }

        public Criteria andRowidLessThan(Integer value) {
            addCriterion("RowID <", value, "rowid");
            return this;
        }

        public Criteria andRowidLessThanOrEqualTo(Integer value) {
            addCriterion("RowID <=", value, "rowid");
            return this;
        }

        public Criteria andRowidIn(List values) {
            addCriterion("RowID in", values, "rowid");
            return this;
        }

        public Criteria andRowidNotIn(List values) {
            addCriterion("RowID not in", values, "rowid");
            return this;
        }

        public Criteria andRowidBetween(Integer value1, Integer value2) {
            addCriterion("RowID between", value1, value2, "rowid");
            return this;
        }

        public Criteria andRowidNotBetween(Integer value1, Integer value2) {
            addCriterion("RowID not between", value1, value2, "rowid");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("Password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("Password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaID is null");
            return this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaID is not null");
            return this;
        }

        public Criteria andAreaidEqualTo(String value) {
            addCriterion("areaID =", value, "areaid");
            return this;
        }

        public Criteria andAreaidNotEqualTo(String value) {
            addCriterion("areaID <>", value, "areaid");
            return this;
        }

        public Criteria andAreaidGreaterThan(String value) {
            addCriterion("areaID >", value, "areaid");
            return this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(String value) {
            addCriterion("areaID >=", value, "areaid");
            return this;
        }

        public Criteria andAreaidLessThan(String value) {
            addCriterion("areaID <", value, "areaid");
            return this;
        }

        public Criteria andAreaidLessThanOrEqualTo(String value) {
            addCriterion("areaID <=", value, "areaid");
            return this;
        }

        public Criteria andAreaidLike(String value) {
            addCriterion("areaID like", value, "areaid");
            return this;
        }

        public Criteria andAreaidNotLike(String value) {
            addCriterion("areaID not like", value, "areaid");
            return this;
        }

        public Criteria andAreaidIn(List values) {
            addCriterion("areaID in", values, "areaid");
            return this;
        }

        public Criteria andAreaidNotIn(List values) {
            addCriterion("areaID not in", values, "areaid");
            return this;
        }

        public Criteria andAreaidBetween(String value1, String value2) {
            addCriterion("areaID between", value1, value2, "areaid");
            return this;
        }

        public Criteria andAreaidNotBetween(String value1, String value2) {
            addCriterion("areaID not between", value1, value2, "areaid");
            return this;
        }

        public Criteria andTradeidIsNull() {
            addCriterion("tradeID is null");
            return this;
        }

        public Criteria andTradeidIsNotNull() {
            addCriterion("tradeID is not null");
            return this;
        }

        public Criteria andTradeidEqualTo(String value) {
            addCriterion("tradeID =", value, "tradeid");
            return this;
        }

        public Criteria andTradeidNotEqualTo(String value) {
            addCriterion("tradeID <>", value, "tradeid");
            return this;
        }

        public Criteria andTradeidGreaterThan(String value) {
            addCriterion("tradeID >", value, "tradeid");
            return this;
        }

        public Criteria andTradeidGreaterThanOrEqualTo(String value) {
            addCriterion("tradeID >=", value, "tradeid");
            return this;
        }

        public Criteria andTradeidLessThan(String value) {
            addCriterion("tradeID <", value, "tradeid");
            return this;
        }

        public Criteria andTradeidLessThanOrEqualTo(String value) {
            addCriterion("tradeID <=", value, "tradeid");
            return this;
        }

        public Criteria andTradeidLike(String value) {
            addCriterion("tradeID like", value, "tradeid");
            return this;
        }

        public Criteria andTradeidNotLike(String value) {
            addCriterion("tradeID not like", value, "tradeid");
            return this;
        }

        public Criteria andTradeidIn(List values) {
            addCriterion("tradeID in", values, "tradeid");
            return this;
        }

        public Criteria andTradeidNotIn(List values) {
            addCriterion("tradeID not in", values, "tradeid");
            return this;
        }

        public Criteria andTradeidBetween(String value1, String value2) {
            addCriterion("tradeID between", value1, value2, "tradeid");
            return this;
        }

        public Criteria andTradeidNotBetween(String value1, String value2) {
            addCriterion("tradeID not between", value1, value2, "tradeid");
            return this;
        }

        public Criteria andActivationIsNull() {
            addCriterion("activation is null");
            return this;
        }

        public Criteria andActivationIsNotNull() {
            addCriterion("activation is not null");
            return this;
        }

        public Criteria andActivationEqualTo(String value) {
            addCriterion("activation =", value, "activation");
            return this;
        }

        public Criteria andActivationNotEqualTo(String value) {
            addCriterion("activation <>", value, "activation");
            return this;
        }

        public Criteria andActivationGreaterThan(String value) {
            addCriterion("activation >", value, "activation");
            return this;
        }

        public Criteria andActivationGreaterThanOrEqualTo(String value) {
            addCriterion("activation >=", value, "activation");
            return this;
        }

        public Criteria andActivationLessThan(String value) {
            addCriterion("activation <", value, "activation");
            return this;
        }

        public Criteria andActivationLessThanOrEqualTo(String value) {
            addCriterion("activation <=", value, "activation");
            return this;
        }

        public Criteria andActivationLike(String value) {
            addCriterion("activation like", value, "activation");
            return this;
        }

        public Criteria andActivationNotLike(String value) {
            addCriterion("activation not like", value, "activation");
            return this;
        }

        public Criteria andActivationIn(List values) {
            addCriterion("activation in", values, "activation");
            return this;
        }

        public Criteria andActivationNotIn(List values) {
            addCriterion("activation not in", values, "activation");
            return this;
        }

        public Criteria andActivationBetween(String value1, String value2) {
            addCriterion("activation between", value1, value2, "activation");
            return this;
        }

        public Criteria andActivationNotBetween(String value1, String value2) {
            addCriterion("activation not between", value1, value2, "activation");
            return this;
        }

        public Criteria andIs50IsNull() {
            addCriterion("IS50 is null");
            return this;
        }

        public Criteria andIs50IsNotNull() {
            addCriterion("IS50 is not null");
            return this;
        }

        public Criteria andIs50EqualTo(String value) {
            addCriterion("IS50 =", value, "is50");
            return this;
        }

        public Criteria andIs50NotEqualTo(String value) {
            addCriterion("IS50 <>", value, "is50");
            return this;
        }

        public Criteria andIs50GreaterThan(String value) {
            addCriterion("IS50 >", value, "is50");
            return this;
        }

        public Criteria andIs50GreaterThanOrEqualTo(String value) {
            addCriterion("IS50 >=", value, "is50");
            return this;
        }

        public Criteria andIs50LessThan(String value) {
            addCriterion("IS50 <", value, "is50");
            return this;
        }

        public Criteria andIs50LessThanOrEqualTo(String value) {
            addCriterion("IS50 <=", value, "is50");
            return this;
        }

        public Criteria andIs50Like(String value) {
            addCriterion("IS50 like", value, "is50");
            return this;
        }

        public Criteria andIs50NotLike(String value) {
            addCriterion("IS50 not like", value, "is50");
            return this;
        }

        public Criteria andIs50In(List values) {
            addCriterion("IS50 in", values, "is50");
            return this;
        }

        public Criteria andIs50NotIn(List values) {
            addCriterion("IS50 not in", values, "is50");
            return this;
        }

        public Criteria andIs50Between(String value1, String value2) {
            addCriterion("IS50 between", value1, value2, "is50");
            return this;
        }

        public Criteria andIs50NotBetween(String value1, String value2) {
            addCriterion("IS50 not between", value1, value2, "is50");
            return this;
        }

        public Criteria andIs100IsNull() {
            addCriterion("IS100 is null");
            return this;
        }

        public Criteria andIs100IsNotNull() {
            addCriterion("IS100 is not null");
            return this;
        }

        public Criteria andIs100EqualTo(String value) {
            addCriterion("IS100 =", value, "is100");
            return this;
        }

        public Criteria andIs100NotEqualTo(String value) {
            addCriterion("IS100 <>", value, "is100");
            return this;
        }

        public Criteria andIs100GreaterThan(String value) {
            addCriterion("IS100 >", value, "is100");
            return this;
        }

        public Criteria andIs100GreaterThanOrEqualTo(String value) {
            addCriterion("IS100 >=", value, "is100");
            return this;
        }

        public Criteria andIs100LessThan(String value) {
            addCriterion("IS100 <", value, "is100");
            return this;
        }

        public Criteria andIs100LessThanOrEqualTo(String value) {
            addCriterion("IS100 <=", value, "is100");
            return this;
        }

        public Criteria andIs100Like(String value) {
            addCriterion("IS100 like", value, "is100");
            return this;
        }

        public Criteria andIs100NotLike(String value) {
            addCriterion("IS100 not like", value, "is100");
            return this;
        }

        public Criteria andIs100In(List values) {
            addCriterion("IS100 in", values, "is100");
            return this;
        }

        public Criteria andIs100NotIn(List values) {
            addCriterion("IS100 not in", values, "is100");
            return this;
        }

        public Criteria andIs100Between(String value1, String value2) {
            addCriterion("IS100 between", value1, value2, "is100");
            return this;
        }

        public Criteria andIs100NotBetween(String value1, String value2) {
            addCriterion("IS100 not between", value1, value2, "is100");
            return this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("orderno is null");
            return this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("orderno is not null");
            return this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("orderno =", value, "orderno");
            return this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("orderno <>", value, "orderno");
            return this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("orderno >", value, "orderno");
            return this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("orderno >=", value, "orderno");
            return this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("orderno <", value, "orderno");
            return this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("orderno <=", value, "orderno");
            return this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("orderno like", value, "orderno");
            return this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("orderno not like", value, "orderno");
            return this;
        }

        public Criteria andOrdernoIn(List values) {
            addCriterion("orderno in", values, "orderno");
            return this;
        }

        public Criteria andOrdernoNotIn(List values) {
            addCriterion("orderno not in", values, "orderno");
            return this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("orderno between", value1, value2, "orderno");
            return this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("orderno not between", value1, value2, "orderno");
            return this;
        }

        public Criteria andIsnewIsNull() {
            addCriterion("IsNew is null");
            return this;
        }

        public Criteria andIsnewIsNotNull() {
            addCriterion("IsNew is not null");
            return this;
        }

        public Criteria andIsnewEqualTo(String value) {
            addCriterion("IsNew =", value, "isnew");
            return this;
        }

        public Criteria andIsnewNotEqualTo(String value) {
            addCriterion("IsNew <>", value, "isnew");
            return this;
        }

        public Criteria andIsnewGreaterThan(String value) {
            addCriterion("IsNew >", value, "isnew");
            return this;
        }

        public Criteria andIsnewGreaterThanOrEqualTo(String value) {
            addCriterion("IsNew >=", value, "isnew");
            return this;
        }

        public Criteria andIsnewLessThan(String value) {
            addCriterion("IsNew <", value, "isnew");
            return this;
        }

        public Criteria andIsnewLessThanOrEqualTo(String value) {
            addCriterion("IsNew <=", value, "isnew");
            return this;
        }

        public Criteria andIsnewLike(String value) {
            addCriterion("IsNew like", value, "isnew");
            return this;
        }

        public Criteria andIsnewNotLike(String value) {
            addCriterion("IsNew not like", value, "isnew");
            return this;
        }

        public Criteria andIsnewIn(List values) {
            addCriterion("IsNew in", values, "isnew");
            return this;
        }

        public Criteria andIsnewNotIn(List values) {
            addCriterion("IsNew not in", values, "isnew");
            return this;
        }

        public Criteria andIsnewBetween(String value1, String value2) {
            addCriterion("IsNew between", value1, value2, "isnew");
            return this;
        }

        public Criteria andIsnewNotBetween(String value1, String value2) {
            addCriterion("IsNew not between", value1, value2, "isnew");
            return this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("Area is null");
            return this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("Area is not null");
            return this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("Area =", value, "area");
            return this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("Area <>", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("Area >", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("Area >=", value, "area");
            return this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("Area <", value, "area");
            return this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("Area <=", value, "area");
            return this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("Area like", value, "area");
            return this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("Area not like", value, "area");
            return this;
        }

        public Criteria andAreaIn(List values) {
            addCriterion("Area in", values, "area");
            return this;
        }

        public Criteria andAreaNotIn(List values) {
            addCriterion("Area not in", values, "area");
            return this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("Area between", value1, value2, "area");
            return this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("Area not between", value1, value2, "area");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List values) {
            addCriterion("Address in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List values) {
            addCriterion("Address not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return this;
        }

        public Criteria andTaxnumberIsNull() {
            addCriterion("TaxNumber is null");
            return this;
        }

        public Criteria andTaxnumberIsNotNull() {
            addCriterion("TaxNumber is not null");
            return this;
        }

        public Criteria andTaxnumberEqualTo(String value) {
            addCriterion("TaxNumber =", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberNotEqualTo(String value) {
            addCriterion("TaxNumber <>", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberGreaterThan(String value) {
            addCriterion("TaxNumber >", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberGreaterThanOrEqualTo(String value) {
            addCriterion("TaxNumber >=", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberLessThan(String value) {
            addCriterion("TaxNumber <", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberLessThanOrEqualTo(String value) {
            addCriterion("TaxNumber <=", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberLike(String value) {
            addCriterion("TaxNumber like", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberNotLike(String value) {
            addCriterion("TaxNumber not like", value, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberIn(List values) {
            addCriterion("TaxNumber in", values, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberNotIn(List values) {
            addCriterion("TaxNumber not in", values, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberBetween(String value1, String value2) {
            addCriterion("TaxNumber between", value1, value2, "taxnumber");
            return this;
        }

        public Criteria andTaxnumberNotBetween(String value1, String value2) {
            addCriterion("TaxNumber not between", value1, value2, "taxnumber");
            return this;
        }

        public Criteria andWorkernameIsNull() {
            addCriterion("WorkerName is null");
            return this;
        }

        public Criteria andWorkernameIsNotNull() {
            addCriterion("WorkerName is not null");
            return this;
        }

        public Criteria andWorkernameEqualTo(String value) {
            addCriterion("WorkerName =", value, "workername");
            return this;
        }

        public Criteria andWorkernameNotEqualTo(String value) {
            addCriterion("WorkerName <>", value, "workername");
            return this;
        }

        public Criteria andWorkernameGreaterThan(String value) {
            addCriterion("WorkerName >", value, "workername");
            return this;
        }

        public Criteria andWorkernameGreaterThanOrEqualTo(String value) {
            addCriterion("WorkerName >=", value, "workername");
            return this;
        }

        public Criteria andWorkernameLessThan(String value) {
            addCriterion("WorkerName <", value, "workername");
            return this;
        }

        public Criteria andWorkernameLessThanOrEqualTo(String value) {
            addCriterion("WorkerName <=", value, "workername");
            return this;
        }

        public Criteria andWorkernameLike(String value) {
            addCriterion("WorkerName like", value, "workername");
            return this;
        }

        public Criteria andWorkernameNotLike(String value) {
            addCriterion("WorkerName not like", value, "workername");
            return this;
        }

        public Criteria andWorkernameIn(List values) {
            addCriterion("WorkerName in", values, "workername");
            return this;
        }

        public Criteria andWorkernameNotIn(List values) {
            addCriterion("WorkerName not in", values, "workername");
            return this;
        }

        public Criteria andWorkernameBetween(String value1, String value2) {
            addCriterion("WorkerName between", value1, value2, "workername");
            return this;
        }

        public Criteria andWorkernameNotBetween(String value1, String value2) {
            addCriterion("WorkerName not between", value1, value2, "workername");
            return this;
        }

        public Criteria andTelIsNull() {
            addCriterion("Tel is null");
            return this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("Tel is not null");
            return this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("Tel =", value, "tel");
            return this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("Tel <>", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("Tel >", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("Tel >=", value, "tel");
            return this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("Tel <", value, "tel");
            return this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("Tel <=", value, "tel");
            return this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("Tel like", value, "tel");
            return this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("Tel not like", value, "tel");
            return this;
        }

        public Criteria andTelIn(List values) {
            addCriterion("Tel in", values, "tel");
            return this;
        }

        public Criteria andTelNotIn(List values) {
            addCriterion("Tel not in", values, "tel");
            return this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("Tel between", value1, value2, "tel");
            return this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("Tel not between", value1, value2, "tel");
            return this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("Mobile is null");
            return this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("Mobile is not null");
            return this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("Mobile =", value, "mobile");
            return this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("Mobile <>", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("Mobile >", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("Mobile >=", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("Mobile <", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("Mobile <=", value, "mobile");
            return this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("Mobile like", value, "mobile");
            return this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("Mobile not like", value, "mobile");
            return this;
        }

        public Criteria andMobileIn(List values) {
            addCriterion("Mobile in", values, "mobile");
            return this;
        }

        public Criteria andMobileNotIn(List values) {
            addCriterion("Mobile not in", values, "mobile");
            return this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("Mobile between", value1, value2, "mobile");
            return this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("Mobile not between", value1, value2, "mobile");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("Email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("Email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("Email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("Email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("Email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("Email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("Email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("Email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("Email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("Email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("Email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("Email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("Email not between", value1, value2, "email");
            return this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("Postcode is null");
            return this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("Postcode is not null");
            return this;
        }

        public Criteria andPostcodeEqualTo(String value) {
            addCriterion("Postcode =", value, "postcode");
            return this;
        }

        public Criteria andPostcodeNotEqualTo(String value) {
            addCriterion("Postcode <>", value, "postcode");
            return this;
        }

        public Criteria andPostcodeGreaterThan(String value) {
            addCriterion("Postcode >", value, "postcode");
            return this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("Postcode >=", value, "postcode");
            return this;
        }

        public Criteria andPostcodeLessThan(String value) {
            addCriterion("Postcode <", value, "postcode");
            return this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(String value) {
            addCriterion("Postcode <=", value, "postcode");
            return this;
        }

        public Criteria andPostcodeLike(String value) {
            addCriterion("Postcode like", value, "postcode");
            return this;
        }

        public Criteria andPostcodeNotLike(String value) {
            addCriterion("Postcode not like", value, "postcode");
            return this;
        }

        public Criteria andPostcodeIn(List values) {
            addCriterion("Postcode in", values, "postcode");
            return this;
        }

        public Criteria andPostcodeNotIn(List values) {
            addCriterion("Postcode not in", values, "postcode");
            return this;
        }

        public Criteria andPostcodeBetween(String value1, String value2) {
            addCriterion("Postcode between", value1, value2, "postcode");
            return this;
        }

        public Criteria andPostcodeNotBetween(String value1, String value2) {
            addCriterion("Postcode not between", value1, value2, "postcode");
            return this;
        }

        public Criteria andFaxesIsNull() {
            addCriterion("Faxes is null");
            return this;
        }

        public Criteria andFaxesIsNotNull() {
            addCriterion("Faxes is not null");
            return this;
        }

        public Criteria andFaxesEqualTo(String value) {
            addCriterion("Faxes =", value, "faxes");
            return this;
        }

        public Criteria andFaxesNotEqualTo(String value) {
            addCriterion("Faxes <>", value, "faxes");
            return this;
        }

        public Criteria andFaxesGreaterThan(String value) {
            addCriterion("Faxes >", value, "faxes");
            return this;
        }

        public Criteria andFaxesGreaterThanOrEqualTo(String value) {
            addCriterion("Faxes >=", value, "faxes");
            return this;
        }

        public Criteria andFaxesLessThan(String value) {
            addCriterion("Faxes <", value, "faxes");
            return this;
        }

        public Criteria andFaxesLessThanOrEqualTo(String value) {
            addCriterion("Faxes <=", value, "faxes");
            return this;
        }

        public Criteria andFaxesLike(String value) {
            addCriterion("Faxes like", value, "faxes");
            return this;
        }

        public Criteria andFaxesNotLike(String value) {
            addCriterion("Faxes not like", value, "faxes");
            return this;
        }

        public Criteria andFaxesIn(List values) {
            addCriterion("Faxes in", values, "faxes");
            return this;
        }

        public Criteria andFaxesNotIn(List values) {
            addCriterion("Faxes not in", values, "faxes");
            return this;
        }

        public Criteria andFaxesBetween(String value1, String value2) {
            addCriterion("Faxes between", value1, value2, "faxes");
            return this;
        }

        public Criteria andFaxesNotBetween(String value1, String value2) {
            addCriterion("Faxes not between", value1, value2, "faxes");
            return this;
        }

        public Criteria andInforIsNull() {
            addCriterion("Infor is null");
            return this;
        }

        public Criteria andInforIsNotNull() {
            addCriterion("Infor is not null");
            return this;
        }

        public Criteria andInforEqualTo(String value) {
            addCriterion("Infor =", value, "infor");
            return this;
        }

        public Criteria andInforNotEqualTo(String value) {
            addCriterion("Infor <>", value, "infor");
            return this;
        }

        public Criteria andInforGreaterThan(String value) {
            addCriterion("Infor >", value, "infor");
            return this;
        }

        public Criteria andInforGreaterThanOrEqualTo(String value) {
            addCriterion("Infor >=", value, "infor");
            return this;
        }

        public Criteria andInforLessThan(String value) {
            addCriterion("Infor <", value, "infor");
            return this;
        }

        public Criteria andInforLessThanOrEqualTo(String value) {
            addCriterion("Infor <=", value, "infor");
            return this;
        }

        public Criteria andInforLike(String value) {
            addCriterion("Infor like", value, "infor");
            return this;
        }

        public Criteria andInforNotLike(String value) {
            addCriterion("Infor not like", value, "infor");
            return this;
        }

        public Criteria andInforIn(List values) {
            addCriterion("Infor in", values, "infor");
            return this;
        }

        public Criteria andInforNotIn(List values) {
            addCriterion("Infor not in", values, "infor");
            return this;
        }

        public Criteria andInforBetween(String value1, String value2) {
            addCriterion("Infor between", value1, value2, "infor");
            return this;
        }

        public Criteria andInforNotBetween(String value1, String value2) {
            addCriterion("Infor not between", value1, value2, "infor");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("Remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("Remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return this;
        }

        public Criteria andWeburlIsNull() {
            addCriterion("WebUrl is null");
            return this;
        }

        public Criteria andWeburlIsNotNull() {
            addCriterion("WebUrl is not null");
            return this;
        }

        public Criteria andWeburlEqualTo(String value) {
            addCriterion("WebUrl =", value, "weburl");
            return this;
        }

        public Criteria andWeburlNotEqualTo(String value) {
            addCriterion("WebUrl <>", value, "weburl");
            return this;
        }

        public Criteria andWeburlGreaterThan(String value) {
            addCriterion("WebUrl >", value, "weburl");
            return this;
        }

        public Criteria andWeburlGreaterThanOrEqualTo(String value) {
            addCriterion("WebUrl >=", value, "weburl");
            return this;
        }

        public Criteria andWeburlLessThan(String value) {
            addCriterion("WebUrl <", value, "weburl");
            return this;
        }

        public Criteria andWeburlLessThanOrEqualTo(String value) {
            addCriterion("WebUrl <=", value, "weburl");
            return this;
        }

        public Criteria andWeburlLike(String value) {
            addCriterion("WebUrl like", value, "weburl");
            return this;
        }

        public Criteria andWeburlNotLike(String value) {
            addCriterion("WebUrl not like", value, "weburl");
            return this;
        }

        public Criteria andWeburlIn(List values) {
            addCriterion("WebUrl in", values, "weburl");
            return this;
        }

        public Criteria andWeburlNotIn(List values) {
            addCriterion("WebUrl not in", values, "weburl");
            return this;
        }

        public Criteria andWeburlBetween(String value1, String value2) {
            addCriterion("WebUrl between", value1, value2, "weburl");
            return this;
        }

        public Criteria andWeburlNotBetween(String value1, String value2) {
            addCriterion("WebUrl not between", value1, value2, "weburl");
            return this;
        }

        public Criteria andByorderIsNull() {
            addCriterion("ByOrder is null");
            return this;
        }

        public Criteria andByorderIsNotNull() {
            addCriterion("ByOrder is not null");
            return this;
        }

        public Criteria andByorderEqualTo(Integer value) {
            addCriterion("ByOrder =", value, "byorder");
            return this;
        }

        public Criteria andByorderNotEqualTo(Integer value) {
            addCriterion("ByOrder <>", value, "byorder");
            return this;
        }

        public Criteria andByorderGreaterThan(Integer value) {
            addCriterion("ByOrder >", value, "byorder");
            return this;
        }

        public Criteria andByorderGreaterThanOrEqualTo(Integer value) {
            addCriterion("ByOrder >=", value, "byorder");
            return this;
        }

        public Criteria andByorderLessThan(Integer value) {
            addCriterion("ByOrder <", value, "byorder");
            return this;
        }

        public Criteria andByorderLessThanOrEqualTo(Integer value) {
            addCriterion("ByOrder <=", value, "byorder");
            return this;
        }

        public Criteria andByorderIn(List values) {
            addCriterion("ByOrder in", values, "byorder");
            return this;
        }

        public Criteria andByorderNotIn(List values) {
            addCriterion("ByOrder not in", values, "byorder");
            return this;
        }

        public Criteria andByorderBetween(Integer value1, Integer value2) {
            addCriterion("ByOrder between", value1, value2, "byorder");
            return this;
        }

        public Criteria andByorderNotBetween(Integer value1, Integer value2) {
            addCriterion("ByOrder not between", value1, value2, "byorder");
            return this;
        }

        public Criteria andBak1IsNull() {
            addCriterion("Bak1 is null");
            return this;
        }

        public Criteria andBak1IsNotNull() {
            addCriterion("Bak1 is not null");
            return this;
        }

        public Criteria andBak1EqualTo(String value) {
            addCriterion("Bak1 =", value, "bak1");
            return this;
        }

        public Criteria andBak1NotEqualTo(String value) {
            addCriterion("Bak1 <>", value, "bak1");
            return this;
        }

        public Criteria andBak1GreaterThan(String value) {
            addCriterion("Bak1 >", value, "bak1");
            return this;
        }

        public Criteria andBak1GreaterThanOrEqualTo(String value) {
            addCriterion("Bak1 >=", value, "bak1");
            return this;
        }

        public Criteria andBak1LessThan(String value) {
            addCriterion("Bak1 <", value, "bak1");
            return this;
        }

        public Criteria andBak1LessThanOrEqualTo(String value) {
            addCriterion("Bak1 <=", value, "bak1");
            return this;
        }

        public Criteria andBak1Like(String value) {
            addCriterion("Bak1 like", value, "bak1");
            return this;
        }

        public Criteria andBak1NotLike(String value) {
            addCriterion("Bak1 not like", value, "bak1");
            return this;
        }

        public Criteria andBak1In(List values) {
            addCriterion("Bak1 in", values, "bak1");
            return this;
        }

        public Criteria andBak1NotIn(List values) {
            addCriterion("Bak1 not in", values, "bak1");
            return this;
        }

        public Criteria andBak1Between(String value1, String value2) {
            addCriterion("Bak1 between", value1, value2, "bak1");
            return this;
        }

        public Criteria andBak1NotBetween(String value1, String value2) {
            addCriterion("Bak1 not between", value1, value2, "bak1");
            return this;
        }

        public Criteria andBak2IsNull() {
            addCriterion("Bak2 is null");
            return this;
        }

        public Criteria andBak2IsNotNull() {
            addCriterion("Bak2 is not null");
            return this;
        }

        public Criteria andBak2EqualTo(String value) {
            addCriterion("Bak2 =", value, "bak2");
            return this;
        }

        public Criteria andBak2NotEqualTo(String value) {
            addCriterion("Bak2 <>", value, "bak2");
            return this;
        }

        public Criteria andBak2GreaterThan(String value) {
            addCriterion("Bak2 >", value, "bak2");
            return this;
        }

        public Criteria andBak2GreaterThanOrEqualTo(String value) {
            addCriterion("Bak2 >=", value, "bak2");
            return this;
        }

        public Criteria andBak2LessThan(String value) {
            addCriterion("Bak2 <", value, "bak2");
            return this;
        }

        public Criteria andBak2LessThanOrEqualTo(String value) {
            addCriterion("Bak2 <=", value, "bak2");
            return this;
        }

        public Criteria andBak2Like(String value) {
            addCriterion("Bak2 like", value, "bak2");
            return this;
        }

        public Criteria andBak2NotLike(String value) {
            addCriterion("Bak2 not like", value, "bak2");
            return this;
        }

        public Criteria andBak2In(List values) {
            addCriterion("Bak2 in", values, "bak2");
            return this;
        }

        public Criteria andBak2NotIn(List values) {
            addCriterion("Bak2 not in", values, "bak2");
            return this;
        }

        public Criteria andBak2Between(String value1, String value2) {
            addCriterion("Bak2 between", value1, value2, "bak2");
            return this;
        }

        public Criteria andBak2NotBetween(String value1, String value2) {
            addCriterion("Bak2 not between", value1, value2, "bak2");
            return this;
        }

        public Criteria andBak3IsNull() {
            addCriterion("Bak3 is null");
            return this;
        }

        public Criteria andBak3IsNotNull() {
            addCriterion("Bak3 is not null");
            return this;
        }

        public Criteria andBak3EqualTo(String value) {
            addCriterion("Bak3 =", value, "bak3");
            return this;
        }

        public Criteria andBak3NotEqualTo(String value) {
            addCriterion("Bak3 <>", value, "bak3");
            return this;
        }

        public Criteria andBak3GreaterThan(String value) {
            addCriterion("Bak3 >", value, "bak3");
            return this;
        }

        public Criteria andBak3GreaterThanOrEqualTo(String value) {
            addCriterion("Bak3 >=", value, "bak3");
            return this;
        }

        public Criteria andBak3LessThan(String value) {
            addCriterion("Bak3 <", value, "bak3");
            return this;
        }

        public Criteria andBak3LessThanOrEqualTo(String value) {
            addCriterion("Bak3 <=", value, "bak3");
            return this;
        }

        public Criteria andBak3Like(String value) {
            addCriterion("Bak3 like", value, "bak3");
            return this;
        }

        public Criteria andBak3NotLike(String value) {
            addCriterion("Bak3 not like", value, "bak3");
            return this;
        }

        public Criteria andBak3In(List values) {
            addCriterion("Bak3 in", values, "bak3");
            return this;
        }

        public Criteria andBak3NotIn(List values) {
            addCriterion("Bak3 not in", values, "bak3");
            return this;
        }

        public Criteria andBak3Between(String value1, String value2) {
            addCriterion("Bak3 between", value1, value2, "bak3");
            return this;
        }

        public Criteria andBak3NotBetween(String value1, String value2) {
            addCriterion("Bak3 not between", value1, value2, "bak3");
            return this;
        }

        public Criteria andBak4IsNull() {
            addCriterion("Bak4 is null");
            return this;
        }

        public Criteria andBak4IsNotNull() {
            addCriterion("Bak4 is not null");
            return this;
        }

        public Criteria andBak4EqualTo(Integer value) {
            addCriterion("Bak4 =", value, "bak4");
            return this;
        }

        public Criteria andBak4NotEqualTo(Integer value) {
            addCriterion("Bak4 <>", value, "bak4");
            return this;
        }

        public Criteria andBak4GreaterThan(Integer value) {
            addCriterion("Bak4 >", value, "bak4");
            return this;
        }

        public Criteria andBak4GreaterThanOrEqualTo(Integer value) {
            addCriterion("Bak4 >=", value, "bak4");
            return this;
        }

        public Criteria andBak4LessThan(Integer value) {
            addCriterion("Bak4 <", value, "bak4");
            return this;
        }

        public Criteria andBak4LessThanOrEqualTo(Integer value) {
            addCriterion("Bak4 <=", value, "bak4");
            return this;
        }

        public Criteria andBak4In(List values) {
            addCriterion("Bak4 in", values, "bak4");
            return this;
        }

        public Criteria andBak4NotIn(List values) {
            addCriterion("Bak4 not in", values, "bak4");
            return this;
        }

        public Criteria andBak4Between(Integer value1, Integer value2) {
            addCriterion("Bak4 between", value1, value2, "bak4");
            return this;
        }

        public Criteria andBak4NotBetween(Integer value1, Integer value2) {
            addCriterion("Bak4 not between", value1, value2, "bak4");
            return this;
        }

        public Criteria andBak5IsNull() {
            addCriterion("Bak5 is null");
            return this;
        }

        public Criteria andBak5IsNotNull() {
            addCriterion("Bak5 is not null");
            return this;
        }

        public Criteria andBak5EqualTo(Integer value) {
            addCriterion("Bak5 =", value, "bak5");
            return this;
        }

        public Criteria andBak5NotEqualTo(Integer value) {
            addCriterion("Bak5 <>", value, "bak5");
            return this;
        }

        public Criteria andBak5GreaterThan(Integer value) {
            addCriterion("Bak5 >", value, "bak5");
            return this;
        }

        public Criteria andBak5GreaterThanOrEqualTo(Integer value) {
            addCriterion("Bak5 >=", value, "bak5");
            return this;
        }

        public Criteria andBak5LessThan(Integer value) {
            addCriterion("Bak5 <", value, "bak5");
            return this;
        }

        public Criteria andBak5LessThanOrEqualTo(Integer value) {
            addCriterion("Bak5 <=", value, "bak5");
            return this;
        }

        public Criteria andBak5In(List values) {
            addCriterion("Bak5 in", values, "bak5");
            return this;
        }

        public Criteria andBak5NotIn(List values) {
            addCriterion("Bak5 not in", values, "bak5");
            return this;
        }

        public Criteria andBak5Between(Integer value1, Integer value2) {
            addCriterion("Bak5 between", value1, value2, "bak5");
            return this;
        }

        public Criteria andBak5NotBetween(Integer value1, Integer value2) {
            addCriterion("Bak5 not between", value1, value2, "bak5");
            return this;
        }

        public Criteria andBak6IsNull() {
            addCriterion("Bak6 is null");
            return this;
        }

        public Criteria andBak6IsNotNull() {
            addCriterion("Bak6 is not null");
            return this;
        }

        public Criteria andBak6EqualTo(Integer value) {
            addCriterion("Bak6 =", value, "bak6");
            return this;
        }

        public Criteria andBak6NotEqualTo(Integer value) {
            addCriterion("Bak6 <>", value, "bak6");
            return this;
        }

        public Criteria andBak6GreaterThan(Integer value) {
            addCriterion("Bak6 >", value, "bak6");
            return this;
        }

        public Criteria andBak6GreaterThanOrEqualTo(Integer value) {
            addCriterion("Bak6 >=", value, "bak6");
            return this;
        }

        public Criteria andBak6LessThan(Integer value) {
            addCriterion("Bak6 <", value, "bak6");
            return this;
        }

        public Criteria andBak6LessThanOrEqualTo(Integer value) {
            addCriterion("Bak6 <=", value, "bak6");
            return this;
        }

        public Criteria andBak6In(List values) {
            addCriterion("Bak6 in", values, "bak6");
            return this;
        }

        public Criteria andBak6NotIn(List values) {
            addCriterion("Bak6 not in", values, "bak6");
            return this;
        }

        public Criteria andBak6Between(Integer value1, Integer value2) {
            addCriterion("Bak6 between", value1, value2, "bak6");
            return this;
        }

        public Criteria andBak6NotBetween(Integer value1, Integer value2) {
            addCriterion("Bak6 not between", value1, value2, "bak6");
            return this;
        }
    }
}