package com.zhiye.common.bean;

import java.io.Serializable;
import java.util.Date;

public class ZyCompany implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Integer companyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.company_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String companyName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.company_address
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String companyAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.post_code
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String postCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.mobile
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_company.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Date updateTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.company_id
     *
     * @return the value of zy_company.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.company_id
     *
     * @param companyId the value for zy_company.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.company_name
     *
     * @return the value of zy_company.company_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.company_name
     *
     * @param companyName the value for zy_company.company_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.company_address
     *
     * @return the value of zy_company.company_address
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.company_address
     *
     * @param companyAddress the value for zy_company.company_address
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.post_code
     *
     * @return the value of zy_company.post_code
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.post_code
     *
     * @param postCode the value for zy_company.post_code
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.mobile
     *
     * @return the value of zy_company.mobile
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.mobile
     *
     * @param mobile the value for zy_company.mobile
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.create_time
     *
     * @return the value of zy_company.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.create_time
     *
     * @param createTime the value for zy_company.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_company.update_time
     *
     * @return the value of zy_company.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_company.update_time
     *
     * @param updateTime the value for zy_company.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}