package com.zhiye.common.bean;

public class ZyDictclass {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_dictclass.DictID
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    private String dictid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_dictclass.DictName
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    private String dictname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_dictclass.Visible
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    private String visible;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_dictclass.DictID
     *
     * @return the value of zy_dictclass.DictID
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public String getDictid() {
        return dictid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_dictclass.DictID
     *
     * @param dictid the value for zy_dictclass.DictID
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public void setDictid(String dictid) {
        this.dictid = dictid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_dictclass.DictName
     *
     * @return the value of zy_dictclass.DictName
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public String getDictname() {
        return dictname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_dictclass.DictName
     *
     * @param dictname the value for zy_dictclass.DictName
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public void setDictname(String dictname) {
        this.dictname = dictname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_dictclass.Visible
     *
     * @return the value of zy_dictclass.Visible
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public String getVisible() {
        return visible;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_dictclass.Visible
     *
     * @param visible the value for zy_dictclass.Visible
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public void setVisible(String visible) {
        this.visible = visible;
    }
}