package com.zhiye.common.bean;

import java.math.BigDecimal;

public class ZyIndexProd {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.ID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.YEAR
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private String year;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.MONTH
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private String month;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.CORPORATIONID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private String corporationid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.PRODUCTID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private String productid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.S01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal s01;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.V01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal v01;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.L01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal l01;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.V02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal v02;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.V03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal v03;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.S02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal s02;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.S03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal s03;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.B01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal b01;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.B02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal b02;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.B03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal b03;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.Q01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal q01;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.Q02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal q02;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_index_prod.Q03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    private BigDecimal q03;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.ID
     *
     * @return the value of zy_index_prod.ID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.ID
     *
     * @param id the value for zy_index_prod.ID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.YEAR
     *
     * @return the value of zy_index_prod.YEAR
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.YEAR
     *
     * @param year the value for zy_index_prod.YEAR
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.MONTH
     *
     * @return the value of zy_index_prod.MONTH
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.MONTH
     *
     * @param month the value for zy_index_prod.MONTH
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.CORPORATIONID
     *
     * @return the value of zy_index_prod.CORPORATIONID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public String getCorporationid() {
        return corporationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.CORPORATIONID
     *
     * @param corporationid the value for zy_index_prod.CORPORATIONID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setCorporationid(String corporationid) {
        this.corporationid = corporationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.PRODUCTID
     *
     * @return the value of zy_index_prod.PRODUCTID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.PRODUCTID
     *
     * @param productid the value for zy_index_prod.PRODUCTID
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.S01
     *
     * @return the value of zy_index_prod.S01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getS01() {
        return s01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.S01
     *
     * @param s01 the value for zy_index_prod.S01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setS01(BigDecimal s01) {
        this.s01 = s01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.V01
     *
     * @return the value of zy_index_prod.V01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getV01() {
        return v01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.V01
     *
     * @param v01 the value for zy_index_prod.V01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setV01(BigDecimal v01) {
        this.v01 = v01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.L01
     *
     * @return the value of zy_index_prod.L01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getL01() {
        return l01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.L01
     *
     * @param l01 the value for zy_index_prod.L01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setL01(BigDecimal l01) {
        this.l01 = l01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.V02
     *
     * @return the value of zy_index_prod.V02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getV02() {
        return v02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.V02
     *
     * @param v02 the value for zy_index_prod.V02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setV02(BigDecimal v02) {
        this.v02 = v02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.V03
     *
     * @return the value of zy_index_prod.V03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getV03() {
        return v03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.V03
     *
     * @param v03 the value for zy_index_prod.V03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setV03(BigDecimal v03) {
        this.v03 = v03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.S02
     *
     * @return the value of zy_index_prod.S02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getS02() {
        return s02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.S02
     *
     * @param s02 the value for zy_index_prod.S02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setS02(BigDecimal s02) {
        this.s02 = s02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.S03
     *
     * @return the value of zy_index_prod.S03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getS03() {
        return s03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.S03
     *
     * @param s03 the value for zy_index_prod.S03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setS03(BigDecimal s03) {
        this.s03 = s03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.B01
     *
     * @return the value of zy_index_prod.B01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getB01() {
        return b01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.B01
     *
     * @param b01 the value for zy_index_prod.B01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setB01(BigDecimal b01) {
        this.b01 = b01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.B02
     *
     * @return the value of zy_index_prod.B02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getB02() {
        return b02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.B02
     *
     * @param b02 the value for zy_index_prod.B02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setB02(BigDecimal b02) {
        this.b02 = b02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.B03
     *
     * @return the value of zy_index_prod.B03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getB03() {
        return b03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.B03
     *
     * @param b03 the value for zy_index_prod.B03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setB03(BigDecimal b03) {
        this.b03 = b03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.Q01
     *
     * @return the value of zy_index_prod.Q01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getQ01() {
        return q01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.Q01
     *
     * @param q01 the value for zy_index_prod.Q01
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setQ01(BigDecimal q01) {
        this.q01 = q01;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.Q02
     *
     * @return the value of zy_index_prod.Q02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getQ02() {
        return q02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.Q02
     *
     * @param q02 the value for zy_index_prod.Q02
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setQ02(BigDecimal q02) {
        this.q02 = q02;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_index_prod.Q03
     *
     * @return the value of zy_index_prod.Q03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public BigDecimal getQ03() {
        return q03;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_index_prod.Q03
     *
     * @param q03 the value for zy_index_prod.Q03
     *
     * @abatorgenerated Mon May 21 20:34:33 CST 2012
     */
    public void setQ03(BigDecimal q03) {
        this.q03 = q03;
    }
}