package com.zhiye.common.bean;

import java.util.Date;

public class ZyLink {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_link.linkId
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private Integer linkId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_link.linkName
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private String linkname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_link.createTime
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private Date createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_link.linkType
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private String linktype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_link.linkImage
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private byte[] linkimage;

    private String link;
    public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_link.linkId
     *
     * @return the value of zy_link.linkId
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_link.linkId
     *
     * @param linkId the value for zy_link.linkId
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_link.linkName
     *
     * @return the value of zy_link.linkName
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_link.linkName
     *
     * @param linkname the value for zy_link.linkName
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_link.createTime
     *
     * @return the value of zy_link.createTime
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_link.createTime
     *
     * @param createtime the value for zy_link.createTime
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_link.linkType
     *
     * @return the value of zy_link.linkType
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public String getLinktype() {
        return linktype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_link.linkType
     *
     * @param linktype the value for zy_link.linkType
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void setLinktype(String linktype) {
        this.linktype = linktype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_link.linkImage
     *
     * @return the value of zy_link.linkImage
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public byte[] getLinkimage() {
        return linkimage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_link.linkImage
     *
     * @param linkimage the value for zy_link.linkImage
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void setLinkimage(byte[] linkimage) {
        this.linkimage = linkimage;
    }
}