package com.zhiye.common.bean;

import java.util.Date;

public class ZyMsg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.msgId
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private Long msgId;

    private int userId;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.userName
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.email
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.mobile
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.gender
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private String gender;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.createTime
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private Date createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_msg.content
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    private String content;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.msgId
     *
     * @return the value of zy_msg.msgId
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.msgId
     *
     * @param msgId the value for zy_msg.msgId
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.userName
     *
     * @return the value of zy_msg.userName
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.userName
     *
     * @param username the value for zy_msg.userName
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.email
     *
     * @return the value of zy_msg.email
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.email
     *
     * @param email the value for zy_msg.email
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.mobile
     *
     * @return the value of zy_msg.mobile
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.mobile
     *
     * @param mobile the value for zy_msg.mobile
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.gender
     *
     * @return the value of zy_msg.gender
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.gender
     *
     * @param gender the value for zy_msg.gender
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.createTime
     *
     * @return the value of zy_msg.createTime
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.createTime
     *
     * @param createtime the value for zy_msg.createTime
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_msg.content
     *
     * @return the value of zy_msg.content
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_msg.content
     *
     * @param content the value for zy_msg.content
     *
     * @abatorgenerated Thu Apr 26 20:58:31 CST 2012
     */
    public void setContent(String content) {
        this.content = content;
    }

	public Long getMsgId() {
		return msgId;
	}

	public void setMsgId(Long msgId) {
		this.msgId = msgId;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
}