package com.zhiye.common.bean;

import java.io.Serializable;

public class ZyPartment implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_partment.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Integer partmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_partment.partment_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String partmentName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_partment.partment_id
     *
     * @return the value of zy_partment.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Integer getPartmentId() {
        return partmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_partment.partment_id
     *
     * @param partmentId the value for zy_partment.partment_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPartmentId(Integer partmentId) {
        this.partmentId = partmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_partment.partment_name
     *
     * @return the value of zy_partment.partment_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getPartmentName() {
        return partmentName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_partment.partment_name
     *
     * @param partmentName the value for zy_partment.partment_name
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPartmentName(String partmentName) {
        this.partmentName = partmentName;
    }
}