package com.zhiye.common.bean;

import java.io.Serializable;

public class ZyProduct implements Serializable {
	
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_product.ID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_product.productID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	private Long productid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_product.product_name
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	private String productName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_product.unit
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	private String unit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column zy_product.orderno
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	private String orderno;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_product.ID
	 * @return  the value of zy_product.ID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_product.ID
	 * @param id  the value for zy_product.ID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_product.productID
	 * @return  the value of zy_product.productID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public Long getProductid() {
		return productid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_product.productID
	 * @param productid  the value for zy_product.productID
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setProductid(Long productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_product.product_name
	 * @return  the value of zy_product.product_name
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_product.product_name
	 * @param productName  the value for zy_product.product_name
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_product.unit
	 * @return  the value of zy_product.unit
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_product.unit
	 * @param unit  the value for zy_product.unit
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column zy_product.orderno
	 * @return  the value of zy_product.orderno
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public String getOrderno() {
		return orderno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column zy_product.orderno
	 * @param orderno  the value for zy_product.orderno
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	private static final long serialVersionUID = 1L;
}