package com.zhiye.common.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ZyProductParams {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public ZyProductParams() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	protected ZyProductParams(ZyProductParams example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table zy_product
	 * @abatorgenerated  Tue Apr 10 10:29:43 CST 2012
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andProductidIsNull() {
			addCriterion("productID is null");
			return this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("productID is not null");
			return this;
		}

		public Criteria andProductidEqualTo(Long value) {
			addCriterion("productID =", value, "productid");
			return this;
		}

		public Criteria andProductidNotEqualTo(Long value) {
			addCriterion("productID <>", value, "productid");
			return this;
		}

		public Criteria andProductidGreaterThan(Long value) {
			addCriterion("productID >", value, "productid");
			return this;
		}

		public Criteria andProductidGreaterThanOrEqualTo(Long value) {
			addCriterion("productID >=", value, "productid");
			return this;
		}

		public Criteria andProductidLessThan(Long value) {
			addCriterion("productID <", value, "productid");
			return this;
		}

		public Criteria andProductidLessThanOrEqualTo(Long value) {
			addCriterion("productID <=", value, "productid");
			return this;
		}

		public Criteria andProductidIn(List values) {
			addCriterion("productID in", values, "productid");
			return this;
		}

		public Criteria andProductidNotIn(List values) {
			addCriterion("productID not in", values, "productid");
			return this;
		}

		public Criteria andProductidBetween(Long value1, Long value2) {
			addCriterion("productID between", value1, value2, "productid");
			return this;
		}

		public Criteria andProductidNotBetween(Long value1, Long value2) {
			addCriterion("productID not between", value1, value2, "productid");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("product_name in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("product_name not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andUnitIsNull() {
			addCriterion("unit is null");
			return this;
		}

		public Criteria andUnitIsNotNull() {
			addCriterion("unit is not null");
			return this;
		}

		public Criteria andUnitEqualTo(String value) {
			addCriterion("unit =", value, "unit");
			return this;
		}

		public Criteria andUnitNotEqualTo(String value) {
			addCriterion("unit <>", value, "unit");
			return this;
		}

		public Criteria andUnitGreaterThan(String value) {
			addCriterion("unit >", value, "unit");
			return this;
		}

		public Criteria andUnitGreaterThanOrEqualTo(String value) {
			addCriterion("unit >=", value, "unit");
			return this;
		}

		public Criteria andUnitLessThan(String value) {
			addCriterion("unit <", value, "unit");
			return this;
		}

		public Criteria andUnitLessThanOrEqualTo(String value) {
			addCriterion("unit <=", value, "unit");
			return this;
		}

		public Criteria andUnitLike(String value) {
			addCriterion("unit like", value, "unit");
			return this;
		}

		public Criteria andUnitNotLike(String value) {
			addCriterion("unit not like", value, "unit");
			return this;
		}

		public Criteria andUnitIn(List values) {
			addCriterion("unit in", values, "unit");
			return this;
		}

		public Criteria andUnitNotIn(List values) {
			addCriterion("unit not in", values, "unit");
			return this;
		}

		public Criteria andUnitBetween(String value1, String value2) {
			addCriterion("unit between", value1, value2, "unit");
			return this;
		}

		public Criteria andUnitNotBetween(String value1, String value2) {
			addCriterion("unit not between", value1, value2, "unit");
			return this;
		}

		public Criteria andOrdernoIsNull() {
			addCriterion("orderno is null");
			return this;
		}

		public Criteria andOrdernoIsNotNull() {
			addCriterion("orderno is not null");
			return this;
		}

		public Criteria andOrdernoEqualTo(String value) {
			addCriterion("orderno =", value, "orderno");
			return this;
		}

		public Criteria andOrdernoNotEqualTo(String value) {
			addCriterion("orderno <>", value, "orderno");
			return this;
		}

		public Criteria andOrdernoGreaterThan(String value) {
			addCriterion("orderno >", value, "orderno");
			return this;
		}

		public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
			addCriterion("orderno >=", value, "orderno");
			return this;
		}

		public Criteria andOrdernoLessThan(String value) {
			addCriterion("orderno <", value, "orderno");
			return this;
		}

		public Criteria andOrdernoLessThanOrEqualTo(String value) {
			addCriterion("orderno <=", value, "orderno");
			return this;
		}

		public Criteria andOrdernoLike(String value) {
			addCriterion("orderno like", value, "orderno");
			return this;
		}

		public Criteria andOrdernoNotLike(String value) {
			addCriterion("orderno not like", value, "orderno");
			return this;
		}

		public Criteria andOrdernoIn(List values) {
			addCriterion("orderno in", values, "orderno");
			return this;
		}

		public Criteria andOrdernoNotIn(List values) {
			addCriterion("orderno not in", values, "orderno");
			return this;
		}

		public Criteria andOrdernoBetween(String value1, String value2) {
			addCriterion("orderno between", value1, value2, "orderno");
			return this;
		}

		public Criteria andOrdernoNotBetween(String value1, String value2) {
			addCriterion("orderno not between", value1, value2, "orderno");
			return this;
		}
	}
}