package com.zhiye.common.bean;

public class ZyRolePremission {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_role_premission.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_role_premission.premission_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private Integer premissionId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_role_premission.role_id
     *
     * @return the value of zy_role_premission.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_role_premission.role_id
     *
     * @param roleId the value for zy_role_premission.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_role_premission.premission_id
     *
     * @return the value of zy_role_premission.premission_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public Integer getPremissionId() {
        return premissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_role_premission.premission_id
     *
     * @param premissionId the value for zy_role_premission.premission_id
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void setPremissionId(Integer premissionId) {
        this.premissionId = premissionId;
    }
}