package com.zhiye.common.bean;

import java.io.Serializable;
import java.util.Date;

public class ZyUser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.userid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private int userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.username
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String username;
    
    private String loginname;
    
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.pid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private int pid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.position
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String position;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.password
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.active
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String active;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String remarks;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.user_type
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private String userType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private int roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private int companyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column zy_user.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private Date updateTime;
    private String rand;
    public String getRand() {
		return rand;
	}

	public void setRand(String rand) {
		this.rand = rand;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.userid
     *
     * @return the value of zy_user.userid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.userid
     *
     * @param userid the value for zy_user.userid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.username
     *
     * @return the value of zy_user.username
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.username
     *
     * @param username the value for zy_user.username
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.pid
     *
     * @return the value of zy_user.pid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int getPid() {
        return pid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.pid
     *
     * @param pid the value for zy_user.pid
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPid(int pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.position
     *
     * @return the value of zy_user.position
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.position
     *
     * @param position the value for zy_user.position
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.password
     *
     * @return the value of zy_user.password
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.password
     *
     * @param password the value for zy_user.password
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.active
     *
     * @return the value of zy_user.active
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.active
     *
     * @param active the value for zy_user.active
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.remarks
     *
     * @return the value of zy_user.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.remarks
     *
     * @param remarks the value for zy_user.remarks
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.user_type
     *
     * @return the value of zy_user.user_type
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.user_type
     *
     * @param userType the value for zy_user.user_type
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.role_id
     *
     * @return the value of zy_user.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.role_id
     *
     * @param roleId the value for zy_user.role_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.company_id
     *
     * @return the value of zy_user.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.company_id
     *
     * @param companyId the value for zy_user.company_id
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.create_time
     *
     * @return the value of zy_user.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.create_time
     *
     * @param createTime the value for zy_user.create_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column zy_user.update_time
     *
     * @return the value of zy_user.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column zy_user.update_time
     *
     * @param updateTime the value for zy_user.update_time
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}