package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zhiye.common.bean.ZyContactType;
import com.zhiye.common.bean.ZyContactTypeParams;

public class ZyContactTypeDAOImpl extends SqlMapClientDaoSupport implements ZyContactTypeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public ZyContactTypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public void insert(ZyContactType record) {
        getSqlMapClientTemplate().insert("zy_contact_type.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int updateByPrimaryKey(ZyContactType record) {
        int rows = getSqlMapClientTemplate().update("zy_contact_type.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyContactType record) {
        int rows = getSqlMapClientTemplate().update("zy_contact_type.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public List selectByParams(ZyContactTypeParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_contact_type.selectByParams", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public ZyContactType selectByPrimaryKey(Integer typeId) {
        ZyContactType key = new ZyContactType();
        key.setTypeId(typeId);
        ZyContactType record = (ZyContactType) getSqlMapClientTemplate().queryForObject("zy_contact_type.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int deleteByParams(ZyContactTypeParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_contact_type.deleteByParams", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int deleteByPrimaryKey(Integer typeId) {
        ZyContactType key = new ZyContactType();
        key.setTypeId(typeId);
        int rows = getSqlMapClientTemplate().delete("zy_contact_type.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int countByParams(ZyContactTypeParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_contact_type.countByParams", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int updateByParamsSelective(ZyContactType record, ZyContactTypeParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_contact_type.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    public int updateByParams(ZyContactType record, ZyContactTypeParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_contact_type.updateByParams", parms);
        return rows;
    }

    /**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyContactType> contatcs = null;
		if (map != null) {
			contatcs = getSqlMapClientTemplate().queryForList(
					"zy_contact_type.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return contatcs;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_contact_type.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}
    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_contact_type
     *
     * @abatorgenerated Fri May 25 23:17:19 CST 2012
     */
    private static class UpdateByParamsParms extends ZyContactTypeParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyContactTypeParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}