package com.zhiye.dao;

import com.zhiye.common.bean.ZyContact;
import com.zhiye.common.bean.ZyContactParams;
import java.util.List;
import java.util.Map;

public interface ZyContactDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int  insert(ZyContact record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int updateByPrimaryKey(ZyContact record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int updateByPrimaryKeySelective(ZyContact record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	List selectByParams(ZyContactParams Params);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	ZyContact selectByPrimaryKey(Integer contactId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int deleteByParams(ZyContactParams Params);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int deleteByPrimaryKey(Integer contactId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int countByParams(ZyContactParams Params);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int updateByParamsSelective(ZyContact record, ZyContactParams Params);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	int updateByParams(ZyContact record, ZyContactParams Params);

	List selectPaginationByPageNum(Map<String, Object> map);

	int countPaginationByPageNum(Map<String, Object> map);

	List selectTypesByContactId(Map<String, Object> map);

	List selectContactByTypeId(Map<String, Object> map);
}