package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zhiye.common.bean.ZyCorporation;
import com.zhiye.common.bean.ZyCorporationParams;
import com.zhiye.common.bean.ZyIndex;

public class ZyCorporationDAOImpl extends SqlMapClientDaoSupport implements ZyCorporationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public ZyCorporationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public void insert(ZyCorporation record) {
        getSqlMapClientTemplate().insert("zy_corporation.insertcorporation", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int updateByPrimaryKey(ZyCorporation record) {
        int rows = getSqlMapClientTemplate().update("zy_corporation.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyCorporation record) {
        int rows = getSqlMapClientTemplate().update("zy_corporation.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public List selectByExample(ZyCorporationParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_corporation.selectByExample", example);
        return list;
    }
    
    public List selectByExample() {
        List list = getSqlMapClientTemplate().queryForList("zy_product.selectByParam");
        return list;
    }
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public ZyCorporation selectByPrimaryKey(Integer rowid) {
        ZyCorporation key = new ZyCorporation();
        key.setRowid(rowid);
        ZyCorporation record = (ZyCorporation) getSqlMapClientTemplate().queryForObject("zy_corporation.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int deleteByExample(ZyCorporationParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_corporation.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int deleteByPrimaryKey(Integer rowid) {
        ZyCorporation key = new ZyCorporation();
        key.setRowid(rowid);
        int rows = getSqlMapClientTemplate().delete("zy_corporation.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int countByExample(ZyCorporationParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_corporation.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int updateByExampleSelective(ZyCorporation record, ZyCorporationParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_corporation.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    public int updateByExample(ZyCorporation record, ZyCorporationParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_corporation.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_corporation
     *
     * @abatorgenerated Wed Apr 18 09:44:47 CST 2012
     */
    private static class UpdateByExampleParms extends ZyCorporationParams {
        private Object record;

        public UpdateByExampleParms(Object record, ZyCorporationParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    /**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyCorporation> corporations = null;
		if (map != null) {
			corporations = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return corporations;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_corporation.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}

	/**
	 * 查询带申报
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationWithIndex(Map<String, Object> map) {
		List<ZyCorporation> corporations = null;
		if (map != null) {
			corporations = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectPaginationWithIndex", map);
		} else {
			return null;
		}
		return corporations;
	}
	/**
	 * 根据地区查找指定日期 的所有企业申报
	 */
	@SuppressWarnings("unchecked")
	public List selectIndexsWithArea(Map<String, Object> map) {
		List<ZyIndex> indexs = null;
		if (map != null) {
			indexs = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectIndexsWithArea", map);
		} else {
			return null;
		}
		return indexs;
	}
	/**
	 * 根据行业查找指定日期 的所有企业申报
	 */
	@SuppressWarnings("unchecked")
	public List selectIndexsWithTrade(Map<String, Object> map) {
		List<ZyIndex> indexs = null;
		if (map != null) {
			indexs = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectIndexsWithTrade", map);
		} else {
			return null;
		}
		return indexs;
	}

	/**
	 * 根据企业ID和是否为IS50来查询
	 */
	@SuppressWarnings("unchecked")
	public List selectIndexsWithCorp(Map<String, Object> map) {
		List<ZyIndex> indexs = null;
		if (map != null) {
			indexs = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectIndexsWithCorp", map);
		} else {
			return null;
		}
		return indexs;
	}

	/**
	 * 查询所有企业的申报
	 */
	@SuppressWarnings("unchecked")
	public List selectAllIndexsByCorp(Map<String, Object> map) {
		List<ZyIndex> indexs = null;
			indexs = getSqlMapClientTemplate().queryForList(
					"zy_corporation.selectAllIndexsByCorp", map);
		return indexs;
	}

}