package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zhiye.common.bean.ZyCorporationProduct;
import com.zhiye.common.bean.ZyCorporationProductParams;

public class ZyCorporationProductDAOImpl extends SqlMapClientDaoSupport implements ZyCorporationProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public ZyCorporationProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public void insert(ZyCorporationProduct record) {
		getSqlMapClientTemplate().insert(
				"zy_corporation_product.insert", record);
	}
	public void insert(String productid) {
		getSqlMapClientTemplate().insert(
				"zy_corporation_product.insertProduct", productid);
	}
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int updateByPrimaryKey(ZyCorporationProduct record) {
		int rows = getSqlMapClientTemplate().update(
				"zy_corporation_product.updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int updateByPrimaryKeySelective(ZyCorporationProduct record) {
		int rows = getSqlMapClientTemplate()
				.update("zy_corporation_product.updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public List selectByParams(Map example) {
		List list = getSqlMapClientTemplate().queryForList(
				"zy_corporation_product.selectByParams",
				example);
		return list;
	}
	 public List<ZyCorporationProduct> selectByParamssCorporationProduct(String id) {
		 ZyCorporationProduct key = new ZyCorporationProduct();
		 key.setCorportationid(id);
		 List<ZyCorporationProduct> record =getSqlMapClientTemplate().queryForList("zy_corporation_product.selectByParamProduct",key);
	        return record;
	    }
	 
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public ZyCorporationProduct selectByPrimaryKey(Integer rowid) {
		ZyCorporationProduct key = new ZyCorporationProduct();
		key.setRowid(rowid);
		ZyCorporationProduct record = (ZyCorporationProduct) getSqlMapClientTemplate().queryForObject("zy_corporation_product.selectByPrimaryKey",key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int deleteByParams(ZyCorporationProductParams example) {
		int rows = getSqlMapClientTemplate().delete(
				"zy_corporation_product.deleteByParams",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int deleteByPrimaryKey(String corportationid) {
		ZyCorporationProduct key = new ZyCorporationProduct();
		key.setCorportationid(corportationid);
		int rows = getSqlMapClientTemplate().delete(
				"zy_corporation_product.deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int countByParams(ZyCorporationProductParams example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"zy_corporation_product.countByParams",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int updateByParamsSelective(ZyCorporationProduct record,
			ZyCorporationProductParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("zy_corporation_product.updateByParamsSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	public int updateByParams(ZyCorporationProduct record,
			ZyCorporationProductParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("zy_corporation_product.updateByParams",
						parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table zy_corporation_product
	 * @abatorgenerated  Wed Apr 18 09:44:47 CST 2012
	 */
	private static class UpdateByParamsParms extends
			ZyCorporationProductParams {
		private Object record;

		public UpdateByParamsParms(Object record,
				ZyCorporationProductParams example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}