package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zhiye.common.bean.ZyContact;
import com.zhiye.common.bean.ZyContactParams;
import com.zhiye.common.bean.ZyContactType;

public class ZyContactDAOImpl extends SqlMapClientDaoSupport implements
		ZyContactDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public ZyContactDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int  insert(ZyContact record) {
		return (Integer)getSqlMapClientTemplate().insert("zy_contact.insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int updateByPrimaryKey(ZyContact record) {
		int rows = getSqlMapClientTemplate().update(
				"zy_contact.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int updateByPrimaryKeySelective(ZyContact record) {
		int rows = getSqlMapClientTemplate().update(
				"zy_contact.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public List selectByParams(ZyContactParams example) {
		List list = getSqlMapClientTemplate().queryForList(
				"zy_contact.selectByParams", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public ZyContact selectByPrimaryKey(Integer contactId) {
		ZyContact key = new ZyContact();
		key.setContactId(contactId);
		ZyContact record = (ZyContact) getSqlMapClientTemplate()
				.queryForObject("zy_contact.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int deleteByParams(ZyContactParams example) {
		int rows = getSqlMapClientTemplate().delete(
				"zy_contact.deleteByParams", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int deleteByPrimaryKey(Integer contactId) {
		ZyContact key = new ZyContact();
		key.setContactId(contactId);
		int rows = getSqlMapClientTemplate().delete(
				"zy_contact.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int countByParams(ZyContactParams example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"zy_contact.countByParams", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int updateByParamsSelective(ZyContact record, ZyContactParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"zy_contact.updateByParamsSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	public int updateByParams(ZyContact record, ZyContactParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"zy_contact.updateByParams", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table zy_contact
	 * 
	 * @abatorgenerated Fri May 25 23:17:19 CST 2012
	 */
	private static class UpdateByParamsParms extends ZyContactParams {
		private Object record;

		public UpdateByParamsParms(Object record, ZyContactParams example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	/**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyContact> contatcs = null;
		if (map != null) {
			contatcs = getSqlMapClientTemplate().queryForList(
					"zy_contact.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return contatcs;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_contact.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}

	/**
	 * 
	 */
	public List selectTypesByContactId(Map<String, Object> map) {
		String m="selectTypesByContactId";
		List<ZyContactType> contatcs = null;
		if (map != null) {
			contatcs = getSqlMapClientTemplate().queryForList(
					"zy_contact.selectTypesByContactId", map);
		} else {
			return null;
		}
		return contatcs;
	}

	public List selectContactByTypeId(Map<String, Object> map) {
		List<ZyContact> contatcs = null;
		if (map != null) {
			contatcs = getSqlMapClientTemplate().queryForList(
					"zy_contact.selectContactByTypeId", map);
		} else {
			return null;
		}
		return contatcs;
	}
}