package com.zhiye.dao;

import com.zhiye.common.bean.ZyContactAndType;
import com.zhiye.common.bean.ZyContactAndTypeParams;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.zhiye.common.bean.ZyContactAndTypeParams;

public class ZyContactAndTypeDAOImpl extends SqlMapClientDaoSupport implements ZyContactAndTypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public ZyContactAndTypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public void insert(ZyContactAndType record) {
		getSqlMapClientTemplate().insert("zy_contact_and_type.insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public List selectByParams(ZyContactAndTypeParams example) {
		List list = getSqlMapClientTemplate().queryForList("zy_contact_and_type.selectByParams", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public int deleteByParams(ZyContactAndTypeParams example) {
		int rows = getSqlMapClientTemplate().delete("zy_contact_and_type.deleteByParams", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public int countByParams(ZyContactAndTypeParams example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("zy_contact_and_type.countByParams", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public int updateByParamsSelective(ZyContactAndType record, ZyContactAndTypeParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate().update("zy_contact_and_type.updateByParamsSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	public int updateByParams(ZyContactAndType record, ZyContactAndTypeParams example) {
		UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
		int rows = getSqlMapClientTemplate().update("zy_contact_and_type.updateByParams", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	private static class UpdateByParamsParms extends ZyContactAndTypeParams {
		private Object record;

		public UpdateByParamsParms(Object record, ZyContactAndTypeParams example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}