package com.zhiye.dao;

import com.zhiye.common.bean.ZyContactAndType;
import com.zhiye.common.bean.ZyContactAndTypeParams;
import java.util.List;
import com.zhiye.common.bean.ZyContactAndTypeParams;

public interface ZyContactAndTypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	void insert(ZyContactAndType record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	List selectByParams(ZyContactAndTypeParams example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	int deleteByParams(ZyContactAndTypeParams example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	int countByParams(ZyContactAndTypeParams example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	int updateByParamsSelective(ZyContactAndType record, ZyContactAndTypeParams example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table zy_contact_and_type
	 * @abatorgenerated  Sat May 26 23:35:23 CST 2012
	 */
	int updateByParams(ZyContactAndType record, ZyContactAndTypeParams example);
}