package com.zhiye.dao;

import com.zhiye.common.bean.ZyDictclass;
import com.zhiye.common.bean.ZyDictclassParams;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ZyDictclassDAOImpl extends SqlMapClientDaoSupport implements ZyDictclassDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public ZyDictclassDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public void insert(ZyDictclass record) {
        getSqlMapClientTemplate().insert("zy_dictclass.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int updateByPrimaryKey(ZyDictclass record) {
        int rows = getSqlMapClientTemplate().update("zy_dictclass.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyDictclass record) {
        int rows = getSqlMapClientTemplate().update("zy_dictclass.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public List selectByExample(ZyDictclassParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_dictclass.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public ZyDictclass selectByPrimaryKey(String dictid) {
        ZyDictclass key = new ZyDictclass();
        key.setDictid(dictid);
        ZyDictclass record = (ZyDictclass) getSqlMapClientTemplate().queryForObject("zy_dictclass.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int deleteByExample(ZyDictclassParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_dictclass.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int deleteByPrimaryKey(String dictid) {
        ZyDictclass key = new ZyDictclass();
        key.setDictid(dictid);
        int rows = getSqlMapClientTemplate().delete("zy_dictclass.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int countByExample(ZyDictclassParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_dictclass.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int updateByExampleSelective(ZyDictclass record, ZyDictclassParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_dictclass.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    public int updateByExample(ZyDictclass record, ZyDictclassParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_dictclass.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_dictclass
     *
     * @abatorgenerated Thu Apr 12 16:35:35 CST 2012
     */
    private static class UpdateByExampleParms extends ZyDictclassParams {
        private Object record;

        public UpdateByExampleParms(Object record, ZyDictclassParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}