package com.zhiye.dao;

import com.zhiye.common.bean.ZyArticle;
import com.zhiye.common.bean.ZyIndex;
import com.zhiye.common.bean.ZyIndexParams;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ZyIndexDAOImpl extends SqlMapClientDaoSupport implements ZyIndexDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public ZyIndexDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public void insert(ZyIndex record) {
        getSqlMapClientTemplate().insert("zy_index.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int updateByPrimaryKey(ZyIndex record) {
        int rows = getSqlMapClientTemplate().update("zy_index.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyIndex record) {
        int rows = getSqlMapClientTemplate().update("zy_index.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public List selectByParams(ZyIndexParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_index.selectByParams", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public ZyIndex selectByPrimaryKey(Integer id) {
        ZyIndex key = new ZyIndex();
        key.setId(id);
        ZyIndex record = (ZyIndex) getSqlMapClientTemplate().queryForObject("zy_index.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int deleteByParams(ZyIndexParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_index.deleteByParams", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        ZyIndex key = new ZyIndex();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("zy_index.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int countByParams(ZyIndexParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_index.countByParams", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int updateByParamsSelective(ZyIndex record, ZyIndexParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_index.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    public int updateByParams(ZyIndex record, ZyIndexParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_index.updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_index
     *
     * @abatorgenerated Fri May 04 16:25:37 CST 2012
     */
    private static class UpdateByParamsParms extends ZyIndexParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyIndexParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    /**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyIndex> indexs = null;
		if (map != null) {
			indexs = getSqlMapClientTemplate().queryForList(
					"zy_index.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return indexs;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_index.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}

}