package com.zhiye.dao;

import com.zhiye.common.bean.ZyLink;
import com.zhiye.common.bean.ZyLinkParams;
import java.util.List;
import java.util.Map;

public interface ZyLinkDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    void insert(ZyLink record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByPrimaryKeyWithoutBLOBs(ZyLink record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByPrimaryKeyWithBLOBs(ZyLink record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByPrimaryKeySelective(ZyLink record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    List selectByParams(ZyLinkParams example);


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    ZyLink selectByPrimaryKey(Integer linkid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int deleteByParams(ZyLinkParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int deleteByPrimaryKey(Integer linkid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int countByParams(ZyLinkParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByParamsSelective(ZyLink record, ZyLinkParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByParamsWithBLOBs(ZyLink record, ZyLinkParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    int updateByParamsWithoutBLOBs(ZyLink record, ZyLinkParams example);
    
    List selectPaginationByPageNum(Map<String, Object> map) ;
    int countPaginationByPageNum(Map<String, Object> map) ;
}