package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.zhiye.common.bean.ZyLink;
import com.zhiye.common.bean.ZyLinkParams;

public class ZyLinkDAOImpl extends SqlMapClientDaoSupport implements ZyLinkDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public ZyLinkDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public void insert(ZyLink record) {
        getSqlMapClientTemplate().insert("zy_link.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByPrimaryKeyWithoutBLOBs(ZyLink record) {
        int rows = getSqlMapClientTemplate().update("zy_link.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByPrimaryKeyWithBLOBs(ZyLink record) {
        int rows = getSqlMapClientTemplate().update("zy_link.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyLink record) {
        int rows = getSqlMapClientTemplate().update("zy_link.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public List selectByParams(ZyLinkParams params) {
        List list = getSqlMapClientTemplate().queryForList("zy_link.selectByParams", params);
        return list;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public ZyLink selectByPrimaryKey(Integer linkId) {
        ZyLink key = new ZyLink();
        key.setLinkId(linkId);
        ZyLink record = (ZyLink) getSqlMapClientTemplate().queryForObject("zy_link.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int deleteByParams(ZyLinkParams params) {
        int rows = getSqlMapClientTemplate().delete("zy_link.deleteByParams", params);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int deleteByPrimaryKey(Integer linkId) {
        ZyLink key = new ZyLink();
        key.setLinkId(linkId);
        int rows = getSqlMapClientTemplate().delete("zy_link.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int countByParams(ZyLinkParams params) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_link.countByParams", params);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByParamsSelective(ZyLink record, ZyLinkParams params) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, params);
        int rows = getSqlMapClientTemplate().update("zy_link.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByParamsWithBLOBs(ZyLink record, ZyLinkParams params) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, params);
        int rows = getSqlMapClientTemplate().update("zy_link.updateByParamsWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    public int updateByParamsWithoutBLOBs(ZyLink record, ZyLinkParams params) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, params);
        int rows = getSqlMapClientTemplate().update("zy_link.updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_link
     *
     * @abatorgenerated Mon Apr 16 20:03:39 CST 2012
     */
    private static class UpdateByParamsParms extends ZyLinkParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyLinkParams params) {
            super(params);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    /**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyLink> links = null;
		if (map != null) {
			links = getSqlMapClientTemplate().queryForList(
					"zy_link.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return links;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_link.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}
}