package com.zhiye.dao;


import com.zhiye.common.bean.ZyMessage;
import com.zhiye.common.bean.ZyMessageParams;
import com.zhiye.common.bean.ZyMsg;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ZyMessageDAOImpl extends SqlMapClientDaoSupport implements ZyMessageDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public ZyMessageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public void insert(ZyMessage record) {
        getSqlMapClientTemplate().insert("zy_message.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int updateByPrimaryKey(ZyMessage record) {
        int rows = getSqlMapClientTemplate().update("zy_message.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyMessage record) {
        int rows = getSqlMapClientTemplate().update("zy_message.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public List selectByParamsWithoutBLOBs(ZyMessageParams params) {
        List list = getSqlMapClientTemplate().queryForList("zy_message.abatorgenerated_selectByParams", params);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public List selectByParamsWithBLOBs(ZyMessageParams params) {
        List list = getSqlMapClientTemplate().queryForList("zy_message.abatorgenerated_selectByParamsWithBLOBs", params);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public ZyMessage selectByPrimaryKey(Long msgId) {
        ZyMessage key = new ZyMessage();
        key.setMsgId(msgId);
        ZyMessage record = (ZyMessage) getSqlMapClientTemplate().queryForObject("zy_message.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int deleteByParams(ZyMessageParams params) {
        int rows = getSqlMapClientTemplate().delete("zy_message.abatorgenerated_deleteByParams", params);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int deleteByPrimaryKey(Long msgId) {
        ZyMessage key = new ZyMessage();
        key.setMsgId(msgId);
        int rows = getSqlMapClientTemplate().delete("zy_message.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int countByParams(ZyMessageParams params) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_message.abatorgenerated_countByParams", params);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int updateByParamsSelective(ZyMessage record, ZyMessageParams params) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, params);
        int rows = getSqlMapClientTemplate().update("zy_message.abatorgenerated_updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    public int updateByParams(ZyMessage record, ZyMessageParams params) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, params);
        int rows = getSqlMapClientTemplate().update("zy_message.abatorgenerated_updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_message
     *
     * @abatorgenerated Thu Apr 26 21:29:17 CST 2012
     */
    private static class UpdateByParamsParms extends ZyMessageParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyMessageParams params) {
            super(params);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }



	/* (non-Javadoc)
	 * @see com.zhiye.dao.ZyMessageDAO#countPaginationByPageNum(java.util.Map)
	 */
	public int countPaginationByPageNum(Map<String, Object> map) {
		// TODO Auto-generated method stub
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_message.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}

	/* (non-Javadoc)
	 * @see com.zhiye.dao.ZyMessageDAO#selectPaginationByPageNum(java.util.Map)
	 */
	public List<ZyMessage> selectPaginationByPageNum(Map<String, Object> params) {
		// TODO Auto-generated method stub
		String m = "selectPaginationByPageNum";
		List<ZyMessage> messages = null;
		if (params != null) {
			messages = getSqlMapClientTemplate().queryForList(
					"zy_message.selectPaginationByPageNum", params);
		} else {
			return null;
		}
		return messages;
	}

	/* (non-Javadoc)
	 * @see com.zhiye.dao.ZyMessageDAO#selectByParams(com.zhiye.common.bean.ZyLinkParams)
	 */


	/* (non-Javadoc)
	 * @see com.zhiye.dao.ZyMessageDAO#selectByParams(com.zhiye.common.bean.ZyMessageParams)
	 */
	public List<ZyMessage> selectByParams(ZyMessageParams params) {
		// TODO Auto-generated method stub
		return null;
	}




}