package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import com.zhiye.common.bean.ZyPremission;
import com.zhiye.common.bean.ZyPremissionParams;

public interface ZyPremissionDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    void insert(ZyPremission record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int updateByPrimaryKey(ZyPremission record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int updateByPrimaryKeySelective(ZyPremission record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    List selectByParams(ZyPremissionParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    ZyPremission selectByPrimaryKey(Integer premissionId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int deleteByParams(ZyPremissionParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int deleteByPrimaryKey(Integer premissionId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int countByParams(ZyPremissionParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int updateByParamsSelective(ZyPremission record, ZyPremissionParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    int updateByParams(ZyPremission record, ZyPremissionParams example);
    
    List<ZyPremission> findSectionIdByRoleId(Map<String,Object> params);
}