package com.zhiye.dao;

import com.zhiye.common.bean.ZyArticle;
import com.zhiye.common.bean.ZyDictionary;
import com.zhiye.common.bean.ZyProduct;
import com.zhiye.common.bean.ZyProductParams;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ZyProductDAOImpl extends SqlMapClientDaoSupport implements ZyProductDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public ZyProductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public void insert(ZyProduct record) {
        getSqlMapClientTemplate().insert("zy_product.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int updateByPrimaryKey(ZyProduct record) {
        int rows = getSqlMapClientTemplate().update("zy_product.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyProduct record) {
        int rows = getSqlMapClientTemplate().update("zy_product.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public List selectByExample(ZyProductParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_product.selectByParams", example);
        return list;
    }
    public List selectByExample() {
        List list = getSqlMapClientTemplate().queryForList("zy_product.selectByParam");
        return list;
    }
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public ZyProduct selectByPrimaryKey(Long id) {
        ZyProduct key = new ZyProduct();
        key.setId(id);
        ZyProduct record = (ZyProduct) getSqlMapClientTemplate().queryForObject("zy_product.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int deleteByExample(ZyProductParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_product.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        ZyProduct key = new ZyProduct();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("zy_product.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int countByExample(ZyProductParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_product.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int updateByExampleSelective(ZyProduct record, ZyProductParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_product.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    public int updateByExample(ZyProduct record, ZyProductParams example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_product.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_product
     *
     * @abatorgenerated Tue Apr 10 10:29:43 CST 2012
     */
    private static class UpdateByExampleParms extends ZyProductParams {
        private Object record;

        public UpdateByExampleParms(Object record, ZyProductParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    /*
     * 列出所有信息
     * */
    /* (non-Javadoc)
     * @see com.zhiye.dao.ZyDictionaryDAO#selectByPrimaryKey(java.lang.String)
     */
    public List selectByPrimaryKey(Map<String, Object> map) {
		String m = "selectByPrimaryKey";
		List<ZyDictionary> dictionarys = null;
		if (map != null) {
			dictionarys = getSqlMapClientTemplate().queryForList(
					"zy_dictionary.selectByPrimaryid", map);
		} else {
			return null;
		}
		return dictionarys;
	}
    /**
	 * 根据MAP进行分页
	 */
	@SuppressWarnings("unchecked")
	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyProduct> products = null;
		if (map != null) {
			products = getSqlMapClientTemplate().queryForList(
					"zy_product.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return products;
	}

	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_product.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}
}