package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import com.zhiye.common.bean.ZyPremission;
import com.zhiye.common.bean.ZyPremissionParams;

public class ZyPremissionDAOImpl  extends CommonDAO  implements ZyPremissionDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public ZyPremissionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void insert(ZyPremission record) {
        getSqlMapClientTemplate().insert("zy_premission.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByPrimaryKey(ZyPremission record) {
        int rows = getSqlMapClientTemplate().update("zy_premission.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyPremission record) {
        int rows = getSqlMapClientTemplate().update("zy_premission.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public List selectByParams(ZyPremissionParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_premission.selectByParams", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public ZyPremission selectByPrimaryKey(Integer premissionId) {
        ZyPremission key = new ZyPremission();
        key.setPremissionId(premissionId);
        ZyPremission record = (ZyPremission) getSqlMapClientTemplate().queryForObject("zy_premission.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int deleteByParams(ZyPremissionParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_premission.deleteByParams", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int deleteByPrimaryKey(Integer premissionId) {
        ZyPremission key = new ZyPremission();
        key.setPremissionId(premissionId);
        int rows = getSqlMapClientTemplate().delete("zy_premission.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int countByParams(ZyPremissionParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_premission.countByParams", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByParamsSelective(ZyPremission record, ZyPremissionParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_premission.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByParams(ZyPremission record, ZyPremissionParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_premission.updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private static class UpdateByParamsParms extends ZyPremissionParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyPremissionParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@SuppressWarnings("unchecked")
	public List<ZyPremission> findSectionIdByRoleId(Map<String, Object> params) {
		return (List<ZyPremission>)getSqlMapClientTemplate().queryForList("zy_premission.findSectionIdByRoleId", params);
	}
}