package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import com.zhiye.common.bean.ZyArticle;
import com.zhiye.common.bean.ZyRole;
import com.zhiye.common.bean.ZyRoleParams;

public class ZyRoleDAOImpl  extends CommonDAO  implements ZyRoleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public ZyRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int insert(ZyRole record) {
        return (Integer)getSqlMapClientTemplate().insert("zy_role.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int updateByPrimaryKey(ZyRole record) {
        int rows = getSqlMapClientTemplate().update("zy_role.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int updateByPrimaryKeySelective(ZyRole record) {
        int rows = getSqlMapClientTemplate().update("zy_role.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public List selectByParams(ZyRoleParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_role.selectByParams", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public ZyRole selectByPrimaryKey(Integer roleId) {
        ZyRole key = new ZyRole();
        key.setRoleId(roleId);
        ZyRole record = (ZyRole) getSqlMapClientTemplate().queryForObject("zy_role.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int deleteByParams(ZyRoleParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_role.deleteByParams", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int deleteByPrimaryKey(Integer roleId) {
        ZyRole key = new ZyRole();
        key.setRoleId(roleId);
        int rows = getSqlMapClientTemplate().delete("zy_role.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int countByParams(ZyRoleParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_role.countByParams", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int updateByParamsSelective(ZyRole record, ZyRoleParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_role.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    public int updateByParams(ZyRole record, ZyRoleParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_role.updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    private static class UpdateByParamsParms extends ZyRoleParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyRoleParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    /**
     * 分页查询
     */
	public int countPaginationByPageNum(Map<String, Object> map) {
		String m = "countPaginationByPageNum";
		int result = 0;
		if (map != null) {
			result = (Integer) getSqlMapClientTemplate().queryForObject(
					"zy_role.countPaginationByPageNum", map);
		} else {
			return 0;
		}
		return result;
	}

	public List selectPaginationByPageNum(Map<String, Object> map) {
		String m = "selectPaginationByPageNum";
		List<ZyRole> roles = null;
		if (map != null) {
			roles = getSqlMapClientTemplate().queryForList(
					"zy_role.selectPaginationByPageNum", map);
		} else {
			return null;
		}
		return roles;
	}
}