package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import com.zhiye.common.bean.ZyRole;
import com.zhiye.common.bean.ZyRoleParams;

public interface ZyRoleDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int insert(ZyRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByPrimaryKey(ZyRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByPrimaryKeySelective(ZyRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    List selectByParams(ZyRoleParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    ZyRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int deleteByParams(ZyRoleParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int countByParams(ZyRoleParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByParamsSelective(ZyRole record, ZyRoleParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByParams(ZyRole record, ZyRoleParams example);
    
    List selectPaginationByPageNum(Map<String, Object> map) ;
    int countPaginationByPageNum(Map<String, Object> map) ;
}