package com.zhiye.dao;

import java.util.List;

import com.zhiye.common.bean.ZyRolePremission;
import com.zhiye.common.bean.ZyRolePremissionParams;

public class ZyRolePremissionDAOImpl  extends CommonDAO  implements ZyRolePremissionDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public ZyRolePremissionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public void insert(ZyRolePremission record) {
        getSqlMapClientTemplate().insert("zy_role_premission.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public List selectByParams(ZyRolePremissionParams example) {
        List list = getSqlMapClientTemplate().queryForList("zy_role_premission.selectByParams", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int deleteByParams(ZyRolePremissionParams example) {
        int rows = getSqlMapClientTemplate().delete("zy_role_premission.deleteByParams", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int countByParams(ZyRolePremissionParams example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("zy_role_premission.countByParams", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByParamsSelective(ZyRolePremission record, ZyRolePremissionParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_role_premission.updateByParamsSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    public int updateByParams(ZyRolePremission record, ZyRolePremissionParams example) {
        UpdateByParamsParms parms = new UpdateByParamsParms(record, example);
        int rows = getSqlMapClientTemplate().update("zy_role_premission.updateByParams", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zy_role_premission
     *
     * @abatorgenerated Fri Mar 23 14:39:07 CST 2012
     */
    private static class UpdateByParamsParms extends ZyRolePremissionParams {
        private Object record;

        public UpdateByParamsParms(Object record, ZyRolePremissionParams example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}