package com.zhiye.dao;

import java.util.List;
import java.util.Map;

import com.zhiye.common.bean.ZyUser;
import com.zhiye.common.bean.ZyUserParams;

public interface ZyUserDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    void insert(ZyUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByPrimaryKey(ZyUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByPrimaryKeySelective(ZyUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    List selectByParams(ZyUserParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    ZyUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int deleteByParams(ZyUserParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int countByParams(ZyUserParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByParamsSelective(ZyUser record, ZyUserParams example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zy_user
     *
     * @abatorgenerated Fri Mar 23 14:39:06 CST 2012
     */
    int updateByParams(ZyUser record, ZyUserParams example);
    
    List selectPaginationByPageNum(Map<String, Object> map) ;
    int countPaginationByPageNum(Map<String, Object> map) ;
}